const questions = [
  {
	"questionId": "1",
	"text": "1. Before migrating to Canada in 1992, the spouses Teodoro and Anita entrusted all their legal papers and documents to their nephew, Atty. Tan. Taking advantage of the situation, Atty. Tan forged a deed of sale, making it appear that he had bought the couple’s property in Quezon City. In 2000, he succeeded in obtaining a TCT over the property in his name. Subsequently, Atty. Tan sold the same property to Luis, who built an auto repair shop on the property. In 2004, Luis registered the deed of conveyance, and title over the property was transferred in his name.In 2006, the spouses Teodoro and Anita came to the Philippines for a visit and discovered what had happened to their property. They immediately hire you as lawyer. What action or actions will you institute in order to vindicate their rights? Explain fully. (4%) (2009 BAR)\n\n"
  },
  {
    "questionId": "2",
    "text": "2.   In 1972, Luciano de la Cruz sold to Chua Chung Chun, a Chinese citizen, a parcel of land in Binondo, Chua died in1990 leaving behind his wife and three children, one of whom, Julian is a naturalized Filipino citizen. Six years after Chua's death, the heirs executed an extrajudicial settlement of estate, and the parcel of land was allocated to Julian. In 2007, Luciano filed suit to recover the land he sold to Chua, alleging that the sale was void because it contravened the Constitution which prohibits the sale of private lands to aliens, Julian moved to dismiss the suit on grounds of pari delicto, laches and acquisitive prescription. Decide the case with reasons. (4%) (2009 BAR)\n\nSUGGESTED ANSWER:\n\nThe case must be dismissed. Julian, who is a naturalized Filipino citizen and to whom the property was allocated in an extra-judicial partition of the estate, is now the new owner of the property. The defect in ownership of the property of Julian's alien father has already been cured by its transfer to Julian. It has been validated by the transfer of the property to a Filipino citizen. Hence, there is no more violation of the constitution because the subject real property is now owned by a Filipino citizen (Halili v. CA 287 SCRA\n465 [1998]). Further, after the lapse of 35 years, laches has set in and the motion to dismiss may be granted, for the failure of Luciano to question the ownership of Chua before its transfer to Julian.\n\n"
  },
  {
    "questionId": "3",
    "text": "3.   Marciano is the owner of a parcel of land through which a river runs out into the sea. The land had been brought under the Torrens System, and is cultivated by Ulpiano and his family as farmworkers therein. Over the years, the river brought silt and sediment from its source up in the\n\nmountains and forests so that gradually the land owned by Marciano increased in area by three hectares. Ulpiano built three huts on this additional area, where he and his two married children live. On this same area. Ulpiano and his family planted peanuts, mongo, beans and vegetables. Ulpiano also regular paid taxes on the land, as shown by tax declarations, for over thirty years.\n\nWhen Marciano learned of the increase in the size of the land he ordered Ulpiano to demolish the huts, and demanded that he be paid his share in the proceeds of the harvest. Marciano claims that under the civil code, the alluvium belongs to him as a registered riparian owner to whose land the accretion attaches, and that his right is enforceable against the whole world. Is Marciano correct? Explain. (3%) (2009 BAR)\n\n"
  },
  {
    "questionId": "4",
    "text": "4.   The properties of Jessica and Jenny, who are neighbors, lie along the banks of the Marikina River.\nAt certain times of the year, the river would swell and as the water recedes, soil, rocks and other\nmaterials are deposited on Jessica’s and Jenny’s properties. This pattern of the river swelling,\nreceding and depositing soil and other materials being deposited on the neighbors’ properties have gone on for many years. Knowing this pattern, Jessica constructed a concrete barrier about 2 meters from her property line and extending towards the river, so that when the water recedes, soil and other materials are trapped within this barrier. After several years, the area between Jessica’s property line to the concrete barrier was completely filled with soil, effectively increasing Jessica’s property by 2 meters. Jenny’s property, where no barrier was constructed, also increased by one meter along the side of the river. x x x If Jessica’s and Jenny’s properties are registered, will the benefit of such registration extend to the increased area of their properties? (2%) (2008 BAR)\n\nSUGGESTED ANSWER:\n\nNo, the registration of Jessica’s and Jenny’s adjoining property does not automatically extend to the accretions. They have to bring their lands under the operation of the Torrens system of land registration following the procedure prescribed in P.D. No. 1529.\n\n"
  },
  {
    "questionId": "5",
    "text": "5.   Assume the two properties are on a cliff adjoining the shore of Laguna Lake. Jessica and Jenny ha hotel built on the properties. They had the earth and rocks excavated from the properties dumped on the adjoining shore, giving rise to a new patch of dry land. Can they validly lay claim to the patch of land? (2%) (2008 BAR)\n\nSUGGESTED ANSWER:\n\nJessica and Jenny cannot validly lay claim to the price of dry land that resulted from the dumping of rocks and earth materials excavated from their properties because it is a reclamation without authority. The land is part of the lakeshore, if not the lakebed, which is inalienable land of the public domain.\n\n"
  },
  {
    "questionId": "6",
    "text": "6.   Juliet offered to sell her house and lot, together with all the furniture and appliances therein, to Dehlma. Before agreeing to purchase the property, Dehlma went to the Register of Deeds to verify Juliet’s title. She discovered that while the property was registered in Juliet’s name under the Land Registration Act, as amended by the Property Registration Decree, it was mortgaged to Elaine to secure a debt of P80,000. Wanting to buy the property, Dehlma told Juliet to redeem the property from Elaine, and gave her an advance payment to be used for purposes of releasing the mortgage on the property. When the mortgage was released, Juliet executed a Deed of Absolute Sale over the property which was duly registered with the Registry of Deeds, and a new TCT was issued in Dehlma’s name. Dehlma immediately took possession over the house and lot and the movables therein Thereafter, Dehlma went to the Assessor’s Office to get a new tax declaration under her name. She was surprised to find out that the property was already declared for tax purposes in the name of XYZ Bank which had foreclosed the mortgage on the property before it was sold to her. XYZ Bank was also the purchaser in the foreclosure sale of the property. At that time the property was still unregistered but XYZ Bank registered the Sheriffs Deed of Conveyance in the day book of the Register of Deeds under Act. 3344 and obtained a tax declaration in its name. Was Dehlma a purchaser in good faith? (2%) (2008 BAR)\n\n"
  },
  {
    "questionId": "7",
    "text": "7.   The properties of Jessica and Jenny, who are neighbors, lie along the banks of the Marikina River.\nAt certain times of the year, the river would swell and as the water recedes, soil, rocks and other\nmaterials are deposited on Jessica’s and Jenny’s properties. This pattern of the river swelling, receding and depositing soil and other materials being deposited on the neighbors’ properties have gone on for many years. Knowing this pattern, Jessica constructed a concrete barrier about 2 meters from her property line and extending towards the river, so that when the water recedes, soil and other materials are trapped within this barrier.\n\nAfter several years, the area between Jessica’s property line to the concrete barrier was completely filled with soil, effectively increasing Jessica’s property by 2 meters. Jenny’s property, where no barrier was constructed, also increased by one meter along the side of the river. XXX\n\nAssume the two properties are on a cliff adjoining the shore of Laguna Lake. Jessica and Jenny ha hotel built on the properties. They had the earth and rocks excavated from the properties dumped on the adjoining shore, giving rise to a new patch of dry land. Can they validly lay claim to the patch of land? (2%) (2008 BAR)\n\n\n"
  },
  {
    "questionId": "8",
    "text": "8.   Bedrock Land & Property Development Corp. is a development company engaged in developing and selling subdivisions, condominium units and industrial estates. In order to replenish its inventories, it embarked on an aggressive land banking program. It employed “scouts” who roam all over the Philippines to look for and conduct investigations on prospective sites for acquisition and development, whether developed, semi-developed or raw land. The management of Bedrock asks you as the company counsel to prepare a manual containing a summary of the pertinent laws and regulations relating to land registration and acquisition of title to land. The manual should include the following items: What is the governing law? (2007 BAR)\n\n"
  },
  {
    "questionId": "9",
    "text": "9.   Mr. and Mrs. Roman and Mr. and Mrs. Cruz filed an application for registration of a parcel of land which after due proceedings was granted by the RTC acting registration as land court. However, before the decree of registration could be issued, the spouses Roman and the spouses Cruz sold the lot to Juan. In the notarized deed of sale, the sellers expressly undertook to submit the deed of sale to the land registration court so that the title to the property would be directly issued in Juan's name. (2015 BAR)\n\na) Is such a stipulation valid? ANSWER:\n\nYES, because when one who is not the owner of the property sells or alienates it and later the seller or grantor acquires title, such title passes by operation of law to the buyer or grantee (Art. 1434).\n\nb) Distinguish a direct attack from a collateral attack on a title."
  },
  {
    "questionId": "10",
    "text": "10.  On March 27, 1980, Cornelio filed an application for land registration involving a parcel of agricultural land that he had bought from Isaac identified as Lot No. 2716 with an area of one (1) hectare. During the trial, Cornelio claimed that he and his predecessors-in-interest had been in open, continuous, uninterrupted, public and adverse possession and occupation of the land for more than thirty (30) years. He likewise introduced in evidence a certification dated February 12,\n1981 citing a presidential declaration to the effect that on June 14, 1980, agricultural lands of the\npublic domain, including the subject matter of the application, were declared alienable and disposable agricultural land.  (2014 BAR)\n\na) If you are the judge, will you grant the application for land registration of Cornelio?"
  },
  {
    "questionId": "11",
    "text": "11.  Manuel was born on 12 March 1940 in a 1000-square meter property where he grew up helping his father, Michael, cultivate the land. Michael has lived on the property since the land was opened for settlement at about the time of the Commonwealth government in 193 5, but for some reason never secured any title to the property other than a tax declaration in his name. He has held the property through the years in the concept of an owner and his stay was uncontested by others. He has also conscientiously and continuously paid the realty taxes on the land. Michael died in 2000 and Manuel - as Michael’s only son and heir -now wants to secure and register title to the land in his own name. He consults you for legal advice as he wants to perfect his title to the land and secure its registration in his name. (2013 BAR)\n\nA)  What are the laws that you need to consider in advising Manuel on how he can perfect his title and register the land in his name? Explain the relevance of these laws to your projected course of action.\n\n"
  },
  {
    "questionId": "12",
    "text": "1.   The contractual relationship between Timothy and Kristopher is a contract of partnership (Art.\n1767) since they have bound themselves to contribute money, property or industry to a common fund, with the intention of dividing the profits of the partnership among themselves. With a seed\nmoney of P500, 000.00 obtained by Timothy through a bank loan, they agreed to divide the profits,\n70% for Kristopher and 30% for Timothy.\n\nHowever, to be more specific, theirs is a limited partnership (Art. 1843) because Timothy does not take part in the control of the business pursuant to Art. 1848. Nevertheless, Timothy is entitled to monthly sales reports in connection with the business, a right enshrined in Art. 1851 of the Civil Code.  (2015 BAR)\n\n"
  },
  {
    "questionId": "13",
    "text": "2.   A lawyer was given an authority by means of a Special Power of Attorney by his client to sell a parcel of land for the amount of P3 Million. Since the client owed the lawyer Pl Million in attorney's fees in a prior case he handled, the client agreed that if the property is sold, the lawyer was entitled to get 5% agent's fee plus Pl Million as payment for his unpaid attorney's fees. The client, however, subsequently found a buyer of his own who was willing to buy the property for a higher amount. Can the client unilaterally rescind the authority he gave in favor of his lawyer? Why or why not? (2015 BAR)\n\n"
  },
  {
    "questionId": "14",
    "text": "X, who was abroad, phoned his brother, Y, authorizing him to sell X’s parcel of land in Pasay. X sent the title to Y by courier service. Acting for his brother, Y executed a notarized deed of absolute sale of the land to Z after receiving payment. What is the status of the sale? (2011 BAR)\nA)  Valid, since a notarized deed of absolute sale covered the transaction and full payment was\nmade.\nB)  Void, since X should have authorized agent Y in writing to sell the land.\nC)  Valid, since Y was truly his brother X’s agent and entrusted with the title needed to effect the\nsale.\nD) Valid, since the buyer could file an action to compel X to execute a deed of sale.\n\n\n"
  },
  {
    "questionId": "15",
    "text": "4.   X was the owner of an unregistered parcel of land in Cabanatuan City. As she was abroad, she advised her sister Y via overseas call to sell the land and sign a contract of sale on her behalf. Y thus sold the land to B1 on March 31, 2001 and executed a deed of absolute sale on behalf of X. B1 fully paid the purchase price.\n\nB2, unaware of the sale of the land to B1, signified to Y his interest to buy it but asked Y for her authority from X. Without informing X that she had sold the land to B1, Y sought X for a written authority to sell. X e-mailed Y an authority to sell the land. Y thereafter sold the land on May 1,\n2001 to B2 on monthly installment basis for two years, the first installment to be paid at the end of\nMay 2001. Who between B1 and B2 has a better right over the land? Explain. (2010 BAR)"
  },
  {
    "questionId": "16",
    "text": "16.\tTimothy executed a Memorandum of Agreement (MOA) with Kristopher setting up a business venture covering three (3) fastfood stores known as \"Hungry Toppings\" that will be established at Mall Uno, Mall Dos, and Mall Tres.  The pertinent provisions of the MOA provides: 1. Timothy shall be considered a partner with thirty percent (30%) share in all of the stores to be set up by Kristopher; 2. The proceeds of the business, after deducting expenses, shall be used to pay the principal amount of P500,000.00 and the interest therein which is to be computed based on the bank rate, representing the bank loan secured by Timothy; 3. The net profits, if any, after deducting the expenses and payments of the principal and interest\nshall be divided as follows: seventy percent (70%) for Kristopher and thirty percent (30%) for\nTimothy; 4. Kristopher shall have a free hand in running the business without any interference from Timothy, his agents, representatives, or assigns , and should such interference happen, Kristopher has the right to buy back the share of Timothy less the amounts already paid on the principal and\nto dissolve the MOA; and 5. Kristopher shall submit his monthly sales report in connection with the business to Timothy.\n\nWhat is the contractual relationship between Timothy and Kristopher? (2014 BAR) "
  },
  {
    "questionId": "17",
    "text": "17.   TRUE or FALSE. Explain your answer in not more than two (2) sentences. x x x [c] An oral partnership is valid. (2009 BAR)\n\nSUGGESTED ANSWER:\n\nTRUE. Partnership is a consensual contract, hence, it is valid even though not in writing.\n\nANOTHER SUGGESTED ANSWER:\n\nTRUE. An oral contract of partnership is valid even though not in writing. However, if it involves contribution of an immovable property or a real right, it must be in a public instrument (Art. 1771, NCC), and the inventory of said property signed by the parties must be attached to said public instrument (Art.\n1773, NCC.), or else it is void.\n\n\nANOTHER SUGGESTED ANSWER:\n\nTRUE. Partnership is a consensual contract, hence, it is valid even though not in writing. The oral contract of partnership is also valid even if an immovable property or real right is contributed thereto. While the law in such a case, requires the partnership to be in a public document, the law does not expressly declare the contract void if not executed in the required form (Article 1409[7], NCC). And there being nothing in the law from which it can be inferred that the said requirement is prohibitory or mandatory (Article 5, NCC), the said oral contract of partnership must also be valid. The interested party may simply require the contract to be made into a public document in order to comply with the required form (Article 1357, NCC). The purpose of the law in requiring a public document is simply to notify the public about the contribution.\n\nB.Obligations of the partners\n\n"
  },
  {
    "questionId": "18",
    "text": "18.   The liability of the partners, including industrial partners for partnership contracts entered into in its name and for its account, when all partnership assets have been exhausted is: (2011 BAR)\nA)  Pro-rata.\nB)  Joint.\nC)  Solidary.\nD) Voluntary."
  },
  {
    "questionId": "19",
    "text": "19.   A, B, and C entered into a partnership to operate a restaurant business. When the restaurant had gone past break-even stage and started to gamer considerable profits, C died. A and B continued the business without dissolving the partnership. They in fact opened a branch of the restaurant, incurring obligations in the process. Creditors started demanding for the payment of their obligations. (2010 BAR)\n\nA)  Who are liable for the settlement of the partnership’s obligations? Explain.\n\nSUGGESTED ANSWER:\nThe two remaining partners, A and B, are liable. When any partner dies and the business is continued without any settlement of accounts as between him or his estate the surviving partners are held liable for continuing the business despite the death of a partner.\n\nB)  What are the creditors’ recourse/s? Explain. (2010 Bar Question)\n\nSUGGESTED ANSWER:\n\nCreditors can file the appropriate actions. For instance, an action for the collection of sum of money against the “partnership at will” and if there are no sufficient funds, the creditors may go after the private properties of A and B. Creditors may also sue the estate of C as the estate is not excused from the liabilities of the partnership even if C is dead already. However, it is only liable up to the time that he remained a partner (Article 1829, 1835, par. 2) The liability of C’s individual property shall be subject first to the payment of his separate debts (Article 1835, New Civil Code).\n\nD.   Limited partnership\n"
  },
  {
    "questionId": "20",
    "text": "1.\tThe term of a 5-year lease contract between X the lessor and Y the lessee, where rents were paid from month to month, came to an end. Still, Y continued using the property with X’s consent. In such a case, it is understood that they impliedly renewed the lease. (2011 BAR)\nA)  from month to month under the same conditions as to the rest. B)  under the same terms and conditions as before.\nC)  under the same terms except the rent which they or the court must fix.\nD) for only a year, with the rent raised by 10% pursuant to the rental control law.\n\nSUGGESTED ANSWER: A\n\n"
  },
  {
    "questionId": "21",
    "text": "2.   (2) A had a 4-storey building which was constructed by Engineer B. After five years, the building developed cracks and its stairway eventually gave way and collapsed, resulting to injuries to some lessees. Who should the lessees sue for damages? (2010 BAR)\nA)  A, the owner\nB)  B, the engineer\nC)  both A & B SUGGESTED ANSWER:\nC. Both A & B.\n\nThe lessee may proceed against A for breach of contract, and against B for tort or statutory liability. The lessor is obliged to make all the necessary repairs in order to keep the leased property suitable for the use to which it has been devoted (Article 1654 (2) NCC). Consequently, the proprietor of a building or structure is responsible for the damages resulting from its total or partial collapse, if it is due to the lack of necessary repairs (Article 1659 NCC).\n\nThe engineer or architect who drew up the plans and specifications for a building is liable for damages if within 15 years from the completion of the structure, the same should collapse by reason of a defect in those plans and specifications, or due to the defects in the ground (Article 1723 NCC).\n\nALTERNATIVE ANSWER:\n\nA. The owner.\n\nThe lessee can sue only the lessor for breach of contract under Article 1659 in relation to Article 1654\nNCC. The lessee cannot sue the architect or the engineer because there was no privity of contract between them.\n\nANOTHER ALTERNATIVE ANSWER:\n\nB. The Engineer.\n\nUnder Article 1723 (NCC), the engineer or architect who drew up the plans and specifications for a building is liable for damages if within 15 years from the completion of the structure, the same should collapse by reason of a defect in those plans and specifications, or due to the defects in the ground.\n\nUnder Article 2192 (NCC), in relation to Article 1723 (NCC), the third person suffering damages may proceed only against the engineer or architect or contractor within the period fixed therein.\n\nB.Rights and obligations of lessor\n\n"
  },
  {
    "questionId": "22",
    "text": "3.   Dorotea leased portions of her 2,000 sq. m. lot to Monet, Kathy, Celia, and Ruth for five (5) years.\nTwo (2) years before the expiration of the lease contract, Dorotea sold the property to PM Realty\nand Development Corporation. The following month, Dorotea and PM Realty stopped accepting rental payments from all the lessees because they wanted to terminate the lease contracts. Due to the refusal of Dorotea to accept rental payments, the lessees , Ruth, et al., filed a complaint for consignation of the rentals before the Regional Trial Court (RTC) of Manila without notifying Dorotea. Is the consignation valid? (2014 BAR)\n\nSUGGESTED ANSWER:\n\nNO, the consignation is not valid. For consignation to be proper, there must be prior notice to the creditor that the debtor is going to consign the payment in court (Art.1257). Even on the assumption that Dorotea was no longer the creditor as she had already sold the property to DM Realty, the facts do not state that the realty corporation was also given notice before filing the case for consignation.\n\n"
  },
  {
    "questionId": "23",
    "text": "4.   Isaac leased the apartment of Dorotea for two (2) years. Six (6) months after, Isaac subleased a portion of the apartment due to financial difficulty. Is the sublease contract valid? (2014 BAR)\n\nSUGGESTED ANSWER:\n\nYES, it is valid if there is no express prohibition for subleasing in the lease contract.\n\n"
  },
  {
    "questionId": "24",
    "text": "5.   Spouses Magtanggol managed and operated a gasoline station on a 1,000 sq.m. lot which they leased from Francisco Bigla-awa. The contract was for a period of three (3) years. When the contract expired, Francisco asked the spouses to peacefully vacate the premises. The spouses ignored the demand and continued with the operation of the gasoline station.\n\nOne month after, Francisco, with the aid of a group of armed men, caused the closure of the gasoline station by constructing fences around it.\n\nWas the act of Francisco and his men lawful? Why? (2014 BAR) SUGGESTED ANSWER:\nNo, the act of Francisco and his men were not lawful. Even when one has a right, such as the right to enjoy his property and to exclude anyone else from the enjoyment of such, a person cannot take the law unto his own hands and must still filed the proper action in court. Even though Francisco had the right to fence his property as part of his right to enjoy it, Spouses Magtanggol have a right to be respected in his possession despite the lapse of their lease (Art 539, NCC). The proper recourse of Francisco is to invoke the proper court and file an action for unlawful detainer.\n\nC.Rights and obligations of lessee\n\n"
  },
  {
    "questionId": "25",
    "text": "6.   Anselmo is the registered owner of a land and a house that his friend Boboy occupied for a nominal rental and on the condition that Boboy would vacate the property on demand. With Anselmo's knowledge,  Boboy  introduced  renovations consisting  of  an  additional  bedroom,  a  covered veranda, and a concrete block fence, at his own expense. Subsequently, Anselmo needed the\n\nproperty as his residence and thus asked Boboy to vacate and turn it over to him. Boboy, despite an extension, failed to vacate the property, forcing Anselmo to send him a written demand to vacate. In his own written reply, Boboy signified that he was ready to leave but Anselmo must first reimburse him the value of the improvements he introduced on the property as he is a builder in good faith. Anselmo refused, insisting that Boboy cannot ask for reimbursement as he is a mere lessee. Boboy responded by removing the improvements and leaving the building in its original state. (2013 BAR)\n\nA)  Resolve Boboy's claim that as a builder in good faith, he should be reimbursed the value of the improvements he introduced.\n\nSUGGESTED ANSWER:\n\nBoboy’s claim that he is a builder in good faith has no basis. A builder in good faith is someone who occupies the property in the concept of an owner. The builder, planter and sower must believe themselves to be owners of the land, or at least, to have a claim of title thereto.\n\nAs Boboy is a lessee of the property, even if he was paying nominal rental, Art. 1678, is applicable. Under this provision, if the lessee makes, in good faith, useful improvements which are suitable to the use for which the lease is intended, without altering the form or substance of the property leased, the lessor upon the termination of the lease, shall pay the lessee one-half of the value of improvements at that time. Should the lessor refuse to reimburse said amount, the lessee may remove the improvements, even though the principal thing may suffer damage thereby.\n\nB)  Can  Boboy be  held  liable  for  damages for  removing the  improvements over  Anselmo's objection?\n\nSUGGESTED ANSWER:\n\nNO. Boboy cannot be held liable for damages. The lessor, Anselmo, refused to reimburse one-half of the value of the improvements, so the lessee, Boboy, may remove the same, even though the principal thing may suffer damage thereby. If in removing the useful improvements Boboy caused more impairment in the property leased than is necessary, he will be liable for damages (Art. 1678).\n\n"
  },
  {
    "questionId": "26",
    "text": "7.   Jude owned a building which he had leased to several tenants. Without informing his tenants, Jude sold the building to Ildefonso. Thereafter, the latter notified all the tenants that he is the new owner of the building. Ildefonso ordered the tenants to vacate the premises within thirty (30) days from notice because he had other plans for the building. The tenants refused to vacate, insisting that they will only do so when the term of their lease shall have expired. Is Ildefonso bound to respect the lease contracts between Jude and his tenants? Explain your answer. (2009 BAR)\n\nSUGGESTED ANSWER:\n\nYes, Ildefonso must respect the lease contracts between Jude and his tenants. While it is true that the said lease contracts were not registered and annotated on the title to the property, Ildefonso is still not an innocent purchaser for value. He ought to know the existence of the lease because the building was already occupied by the tenants at the time he bought it. Applying the principle of caveat emptor, he should have checked and known the status of the occupants or their right to occupy the building before buying it.\n\n"
  },
  {
    "questionId": "27",
    "text": "8.   Dux leased his house to Iris for a period of 2 years, at the rate of P25,000.00 monthly, payable annually in advance. The contract stipulated that it may be renewed for another2-year period upon mutual agreement of the parties. The contract also granted Iris the right of first refusal to purchase the property at any time during the lease, if Dux decides to sell the property at the same price that the property is offered for sale to a third party. Twenty-three months after execution of the lease\n\ncontract, Dux sold the house to his mother for P2 million. Iris claimed that the sale was a breach of her right of first refusal. Dux said there was no breach because the property was sold to his mother who is not a third party. Iris filed an action to rescind the sale and to compel Dux to sell the property to her at the same price. Alternatively, she asked the court to extend the lease for another 2 years on the same terms. xxx\n\nWill the alternative prayer for extension of the lease prosper? (2008 BAR) SUGGESTED ANSWER:\nNo, the extension of the lease should be upon the mutual agreement of the parties.\n"
  }
];