const questions = [
  {
    "questionId": "1",
    "text": "1.\tMabuhay Elementary School organized a field trip for its Grade VI students in Fort Santiago, Manila Zoo, and Star City. To be able to join, the parents of the students had to sign a piece of paper that reads as follows:  \"I allow my child (name of student), Grade – Section, to join the school’s field trip on February 14, 2014.  I will not file any claim against the school, administrator or teacher in case something happens to my child during the trip.\"  Joey, a 7-year-old student of Mabuhay Elementary School was bitten by a snake while the group was touring Manila Zoo. The parents of Joey sued the school for damages. The school, as a defense, presented the waiver signed by Joey’s parents.\n\nWas there a valid waiver of right to sue the school? Why? (2014 BAR)\n\n\n\n"
  },
  {
    "questionId": "2",
    "text": "2.   Jovencio operated a school bus to ferry his two sons and five of their schoolmates from their houses to their school, and back. The parents of the five schoolmates paid for the service. One morning, Porfirio, the driver, took a short cut on the way to school because he was running late, and drove across an unmanned railway crossing. At the time, Porfirio was wearing earphones because he loved to hear loud music while driving. As he crossed the railway tracks, a speeding PNR train loudly blared its horn to warn Porfirio, but the latter did not hear the horn because of the loud music. The train inevitably rammed into the school bus. The strong impact of the collision between the school bus and the train resulted in the instant death of one of the classmates of Jovencio’s younger son.\n\nThe parents of the fatality sued Jovencio for damages based on culpa contractual alleging that Jovencio was a common carrier; Porfirio for being negligent; and the PNR for damages based on culpa aquiliana.\n\nJovencio denied being a common carrier. He insisted that he had exercised the diligence of a good father of a family in supervising Porfirio, claiming that the latter had had no history of negligence or recklessness before the fatal accident. (2017 BAR)\n\nA)  Did his operation of the school bus service for a limited clientele render Jovencio a common carrier? Explain your answer.\n\nB)  In accordance with your answer to the preceding question, state the degree of diligence to be observed by Jovencio, and the consequences thereof. Explain your answer. (Negligence, Standard of Care)\nC)  Assuming that the fatality was a minor of only 15 years of age who had no earning capacity at the time of his death because he was still a student in high school, and the trial court is minded to award indemnity, what may possibly be the legal and factual justifications for the award of loss of earning capacity? Explain your answer. (In case of Death)\n\n"
  },
  {
    "questionId": "3",
    "text": "3.   Dr. Jack, a surgeon, holds clinic at the St. Vincent’s Hospital and pays rent to the hospital. The fees of Dr. Jack are paid directly to him by the patient or through the cashier of the hospital. The hospital publicly displays in the lobby the names and specializations of the doctors associated or accredited by it, including that of Dr. Jack. Marta engaged the services of Dr. Jack because of recurring stomach pain. It was diagnosed that she is suffering from cancer and had to be operated on. Before the operation, she was asked to sign a “consent for hospital care,” which reads.\n\n\n“Permission is hereby given to the medical, nursing and laboratory staff of the St. Vincent’s Hospital to perform such procedures and to administer such medications and treatments as may be deemed necessary or advisable by the physicians of this hospital for and during the confinement.”\n\nAfter the surgery, the attending nurses reported that two (2) sponges were missing. Later, Marta died due to complications brought about by the sponges that were left in her stomach. The husband of Marta sued the hospital and Dr. Jack for damages arising from negligence in the medical procedure. The hospital raised the defense that Dr. Jack is not its employee as it did not hire Dr. Jack nor pay him any salary or compensation. It has absolutely no control over the medical services and treatment being provided by Dr. Jack. Dr. Jack even signed an agreement that he holds the hospital free and harmless from any liability arising from his medical practice in the hospital.\n\nIs St. Vincent’s Hospital liable for the negligence of Dr. Jack? Explain your answer. (2016 BAR)"
  },
  {
    "questionId": "4",
    "text": "4.   Liwayway Vinzons-Chato was then the Commissioner of Internal Revenue while Fortune Tobacco Corporation is an entity engaged in the manufacture of different brands of cigarettes, among which are \"Champion,\" \"Hope,\" and \"More\" cigarettes.\n\nFortune filed a complaint against Vinzons-Chato to recover damages for the alleged violation of its constitutional rights arising from Vinzons-Chato’s issuance of Revenue Memorandum Circular No. 37-934 (which re-classified Fortune cigarettes as locally manufactured with foreign brands and thereby imposed higher taxes), which the Supreme Court later declared invalid.\n\nVinzons-Chato filed a Motion to dismiss arguing that she cannot be held liable for damages for acts she performed while in the discharge of her duties as BIR Commissioner. Is she correct? Explain. (2012 BAR)"
  },
  {
    "questionId": "5",
    "text": "5.   Lennie bought a business class ticket from Alta Airlines. As she checked in, the manager downgraded her to economy on the ground that a Congressman had to be accommodated in the business class. Lennie suffered the discomfort and embarrassment of the downgrade. She sued the airlines for quasi-delict but Alta Airlines countered that, since her travel was governed by a contract between them, no quasi-delict could arise. Is the airline correct? (2011 BAR)\n\nA)  No, the breach of contract may in fact be tortious as when it is tainted as in this case with arbitrariness, gross bad faith, and malice.\nB)  No, denying Lennie the comfort and amenities of the business class as provided in the ticket is a tortious act.\nC)  Yes, since the facts show a breach of contract, not a quasi-delict.\nD) Yes, since quasi-delict presupposes the absence of a pre-existing contractual relation between\nthe parties.\nE)  No, the breach of contract may in fact be tortious as when it is tainted as in this case with arbitrariness, gross bad faith, and malice.\nF)  No, denying Lennie the comfort and amenities of the business class as provided in the ticket\nis a tortious act.\nG)  Yes, since the facts show a breach of contract, not a quasi-delict.\nH) Yes, since quasi-delict presupposes the absence of a pre-existing contractual relation between the parties.\n\n"
  },
  {
    "questionId": "6",
    "text": "6.   Virgilio  owned  a  bare  and  simple  swimming pool  in  his  garden.  MB,  a  7-year  old  child, surreptitiously entered  the  garden  and  merrily romped around the  ledges  of  the  pool.  He accidentally tripped, fell into the pool, and drowned. MB’s parents sued Virgilio for damages arising from their child’s death, premised on the principle of \"attractive nuisance\". Is Virgilio liable for the death of MB? (2011 BAR)\n\nA)  No, the child was 7 years old and knew the dangers that the pool offered.\nB)  Yes, being an attractive nuisance, Virgilio had the duty to prevent children from coming near it.\nC)  No, since the pool was bare and had no enticing or alluring gadgets, floats, or devices in it that would attract a 7-year old child.\nD) Yes, since Virgilio did not cover the swimming pool while not in use to prevent children from falling into it.\n\n"
  },
  {
    "questionId": "7",
    "text": "7.   Define quasi tort. Who are the persons liable under quasi torts and what are the defenses available to them? (2010 BAR)\n\nNOTE: It is recommended that the examiner exercise leniency and liberality in grading the answers given to this question. The term quasi-tort is not a part of legal developments in civil law. In Philippine legal tradition, quasi-delict has been treated as the closest civil law equivalent of the common law tort. In fact, in a number of Supreme Court decisions, the two terms have been\n\nconsidered synonymous. In reality, however, the common law tort is much broader in scope than the civil law quasi-delict.\n\nIn recent developments in common law, the concept of “quasi-torts” can be considered as the closest common law equivalent of the civil law concept of quasi-delict. This is because it is argued that the growing recognition of quasi-torts as a source of obligation is hinged on the acceptance at common law of the civil law principles of quasi-delict.\n\n"
  },
  {
    "questionId": "8",
    "text": "8.   On May 5, 1989, 16-year old Rozanno, who was issued a student permit, drove to school a car, a gift from his parents. On even date, as his class was scheduled to go on a field trip, his teacher requested him to accommodate in his car, as he did, four (4) of his classmates because the van rented by the school was too crowded. On the way to a museum which the students were scheduled to visit, Rozanno made a wrong maneuver, causing a collision with a jeepney. One of his classmates died. He and the three (3) others were badly injured.\n\nxxx\n\nB. Who is liable for] the damage to the jeepney? Explain. (2010 BAR)"
  },
  {
    "questionId": "9",
    "text": "9.   Under the same facts, except the date of occurrence of the incident, this time in mid-1994, what would be your answer? Explain. (2010 BAR)\n\n\n"
  },
  {
    "questionId": "10",
    "text": "10.  Primo owns a pet iguana which he keeps in a man- made pond enclosed by a fence situated in his residential lot. A typhoon knocked down the fence of the pond and the iguana crawled out of the gate of Primo’s residence. N, a neighbor who was passing by, started throwing stones at the iguana, drawing the iguana to move toward him. N panicked and ran but tripped on something and suffered a broken leg.\n\nIs anyone liable for N’s injuries? Explain. (2010 BAR)\n\n"
  },
  {
    "questionId": "11",
    "text": "11.  Rommel’s private car, while being driven by the regular family driver, Amado, hits a pedestrian causing the latter’s death. Rommel is not in the car when the incident happened.\n\nIs Rommel liable for damages to the heirs of the deceased? Explain. (2009 BAR)"
  },
  {
    "questionId": "12",
    "text": "12.  Would your answer be the same if Rommel was in the car at the time of the accident? Explain. (2009 BAR)\n\n"
  },
  {
    "questionId": "13",
    "text": "13.  Explain the following concepts and doctrines and give an example of each: x x x (b) doctrine of discovered peril (last clear chance) (2007 BAR)\n\n"
  },
  {
    "questionId": "14",
    "text": "14.  A driver of a bus owned by company Z ran over a boy who died instantly. A criminal case for reckless imprudence resulting in homicide was filed against the driver. He was convicted and was ordered to pay P2 Million in actual and moral damages to the parents of the boy who was an honor student and had a bright future. Without even trying to find out if the driver had assets or means to pay the award of damages, the parents of the boy filed a civil action against the bus company to make it directly liable for the damages. (2015 BAR)\n\nA)  Will their action prosper?\nB)  If the parents of the boy do not wish to file a separate civil action against the bus company,\ncan they still make the bus company liable if the driver cannot' pay the award for damages? If so, what is the nature of the employer's liability and how may civil damages be satisfied?\n\n"
  },
  {
    "questionId": "15",
    "text": "15.  A collision occurred at an intersection involving a bicycle and a taxicab. Both the bicycle rider (a businessman then doing his morning exercise) and the taxi driver claimed that the other was at fault. Based on the police report, the bicycle crossed the intersection first but the taxicab, crossing at a fast clip from the bicycle's left, could not brake in time and hit the bicycle's rear wheel, toppling it and throwing the bicycle rider into the sidewalk 5 meters away.\n\nThe bicycle rider suffered a fractured right knee, sustained when he fell on his right side on the concrete side walk. He was hospitalized and was subsequently operated on, rendering him immobile for 3 weeks and requiring physical rehabilitation for another 3 months. In his complaint for damages, the rider prayed for the award of P1,000,000 actual damages, P200,000 moral damages, P200,000 exemplary damages, P100,000 nominal damages and P50,000 attorney's fees.\n\nAssuming the police report to be correct and as the lawyer for the bicycle rider, what evidence (documentary and testimonial) and legal arguments will you present in court to justify the damages that your client claims? (2013 BAR)\n\n"
  },
  {
    "questionId": "16",
    "text": "16. Roberto was in Nikko Hotel when he bumped into a friend who was then on her way to a wedding reception being held in said hotel. Roberto alleged that he was then invited by his friend to join\n\nher at the wedding reception and carried the basket full of fruits which she was bringing to the affair. At the reception, the wedding coordinator of the hotel noticed him and asked him, allegedly in a loud voice, to leave as he was not in the guest list. He retorted that he had been invited to the affair by his friend, who however denied doing so. Deeply embarrassed by the incident, Roberto then sued the hotel for damages under Articles 19 and 21 of the Civil Code. Will Roberto’s action prosper? Explain. (2012 BAR)\n\n"
  },
  {
    "questionId": "17",
    "text": "17.  Ricky donated P 1 Million to the unborn child of his pregnant girlfriend, which she accepted. After six (6) months of pregnancy, the fetus was born and baptized as Angela. However, Angela died 20 hours after birth. Ricky sought to recover the P 1 Million. Is Ricky entitled to recover? Explain.\n\nSUGGESTED ANSWER:\n\nYES, Ricky is entitled to recover the P1,000,000.00. The NCC considers a fetus is considered a person for purposes favorable to it provided it is born later in accordance with the provision of the NCC. While the donation is favorable to the fetus, the donation did not take effect because the fetus was not born in accordance with the NCC.\n\nTo be considered born, the fetus that had an intrauterine life of less than seven (7) months should live for\n24 hours from its complete delivery from the mother’s womb. Since Angela had an intrauterine life of less than seven (7) months but did not live for 24 hours, she was not considered born and, therefore, did not become a person (Art. 41). Not being a person, she has no juridical capacity to be a donee, hence, the donation to her did not take effect., and the amount donated may be recovered. To retain it will be unjust enrichment.\n\n"
  },
  {
    "questionId": "18",
    "text": "18.  Peter, a resident of Cebu City, sent through Reliable Pera Padala (RPP) the amount of P20,000.00 to his daughter, Paula, for the payment of her tuition fee. Paula went to an RPP branch but was informed that there was no money remitted to her name. Peter inquired from RPP and was informed that there was a computer glitch and the money was credited to another person. Peter and Paula sued RPP for actual damages, moral damages and exemplary damages. The trial court ruled that there was no proof of pecuniary loss to the plaintiffs but awarded moral damages of. P20,000.00 and exemplary damages of P5,000.00. On appeal, RPP questioned the award of moral and exemplary damages. Is the trial court correct in awarding moral and exemplary damages? Explain. (2016 BAR)\n\n\nSUGGESTED ANSWER:\n\nNo, the trial court is not correct in awarding moral and exemplary damages. The damages in this case are prayed for based on the breach of contract committed by RPP in failing to deliver the sum of money to Paula. Under the provisions of the Civil Code, in breach of contract, moral damages may be recovered when the defendant acted in bad faith or was guilty of gross negligence (amounting to bad faith) or in wanton disregard of his contractual obligation. In the same fashion, to warrant the award of exemplary damages, the wrongful act must be accomplished by bad faith, and the guilty party acted in a wanton, fraudulent, reckless or malevolent manner.\nBad faith imports a dishonest purpose or some moral obliquity and conscious doing of a wrong, a breach\nof known duty through some motive or interest or ill will that partakes of the nature of fraud. In this case,\nhowever, RPP’s breach was due to a computer glitch which at most can be considered as negligence on its part, but definitely does not constitute bad faith or fraud as would warrant the award of moral and exemplary damages.\n\nALTERNATIVE ANSWER:\n\nIf the trial court finds that there was gross negligence on the part of RPP, the award of moral damages and exemplary damages would be proper. RPP merely alleged that the failure to remit the money to Paula was caused by a computer glitch, but this bare assertion does not preclude the possibility that the trial court found gross negligence (equivalent to bad faith) on the part of RPP. Moral damages may be awarded in cases of breaches of contract where the defendant acted fraudulently or in bad faith.\n\n"
  },
  {
    "questionId": "19",
    "text": "19.  Rodolfo, married to Sharon, had an illicit affair with his secretary, Nanette, a 19- year old girl, and begot a baby girl, Rona. Nanette sued Rodolfo for damages: actual, for hospital and other medical expenses in delivering the child by caesarean section; moral, claiming that Rodolfo promised to marry her, representing that he was single when, in fact, he was not; and exemplary, to teach a lesson to like-minded Lotharios.\n\nIf you were the judge, would you award all the claims of Nanette? Explain. (2009 BAR) SUGGESTED ANSWER:\nIf Rodolfo’s marriage could not have been possibly known to Nanette or there is no gross negligence on\nthe part of Nanette, Rodolfo could be held liable for moral damages.\nIf there is gross negligence in a suit for quasi-delict, exemplary damages could be awarded.\n\n"
  },
  {
    "questionId": "20",
    "text": "20. With regard to an award of interest in the concept of actual and compensatory damages, please state the guidelines regarding the manner of computing legal interest in the following situations:\n\nA)  when the obligation is breached and it consists in the payment of a sum of money like a loan or forbearance of money;\nB)  when the obligation does not constitute a loan or forbearance of money. Consider the issuance of BSP-MB Circular No. 799, which became effective on July 1, 2013.\n\nSUGGESTED ANSWER\n\n(A) When the obligation is breached and it consists in the payment of a sum of money like a loan or forbearance of money, in the absence of stipulation, the rate of interest shall be the legal rate of 6% per annum (Article 2209, NCC), which was increased to 12% per NB Circular No. 905 (Series of 1982), to be computed from default. The twelve percent 12% per annum legal interest shall apply only until June 30,\n"
  }
];