const questions =  [
  {
    "questionId": "1",
    "text": "1.   Distinguish commodatum from mutuum. (2017 BAR)"
  },
  {
    "questionId": "2",
    "text": "2.   Cruz lent Jose his car until Jose finished his Bar exams. Soon after Cruz delivered the car, Jose brought it to Mitsubishi Cubao for maintenance check up and incurred costs of P8,000. Seeing the car's peeling and faded paint, Jose also had the car repainted for P10,000. Answer the two questions below based on these common facts. (2013 BAR)\n\nAfter the bar exams, Cruz asked for the return of his car. Jose said he would return it as soon as Cruz has reimbursed him for the car maintenance and repainting costs of P 18,000. Is Jose's refusal justified?\n\nA)  No, Jose's refusal is not justified. In this kind of contract, Jose is obliged to pay for all the expenses incurred for the preservation of the thing loaned.\nB)  Yes, Jose's refusal is justified. He is obliged to pay forall the ordinary and extraordinary expenses, but subject to reimbursement from Cruz.\nC)  Yes, Jose's refusal is justified. The principle of unjust enrichment warrants the reimbursement of Jose's expenses.\nD) No, Jose's refusal is not justified. The expenses he incurred are useful for the preservation of the thing loaned. It is Jose's obligation to shoulder these useful expenses.\n\nSUGGESTED ANSWER:\n\nD.\n\nIn commodatum, the bailee is obliged to pay for the ordinary expenses for the use and preservation of the thing loaned (Art. 1941, Civil Code). The bailee, Jose, has no right of retention on the ground that Cruz has not reimbursed the useful expenses for preservation which Jose incurred.\n\n"
  },
  {
    "questionId": "3",
    "text": "3.   The borrower in a contract of loan or mutuum must pay interest to the lender. (2012 BAR) A)  If there is an agreement in writing to the effect.\nB)  As a matter of course.\n\nC)  If the amount borrowed is very large.\nD) If the lender so demands at the maturity date.\n\nSUGGESTED ANSWER: A\n\n"
  },
  {
    "questionId": "4",
    "text": "4.   Siga-an granted a loan to Villanueva in the amount ofP540, 000.00. Such agreement was not reduced to writing. Siga-an demanded interest which was paid by Villanueva in cash and checks. The total amount Villanueva paid accumulated to P 1, 200, 000.00. Upon advice of her lawyer, Villanueva demanded for the return of the excess amount of P 660, 000.00 which was ignored by Siga-an. (2012 BAR)\n\nA)  Is the payment of interest valid? Explain. SUGGESTED ANSWER:\nNO. Art. 1956, provides that \"no interest shall be due unless it has been expressly stipulated in writing.\"\n\nB)  Is solutio indebiti applicable? Explain. SUGGESTED ANSWER:\nYES. Under Art. 1960, solutio indebiti shall be applied if the borrower pays interest when there has been no stipulation thereof. Villanueva paid in excess of P660.000 representing interest payment which is not due. Therefore, he can demand its return.\n\n"
  },
  {
    "questionId": "5",
    "text": "5.   During the bar exam month, Jose lent the car to his girlfriend, Jolie, who parked the car at the Mall of Asia's open parking lot, with the ignition key inside the car. Car thieves broke into and took the car. (2012 BAR)\n\nIs Jose liable to Cruz for the loss of the car due to Jolie's negligence?\n\nA)  No, Jose is not liable to Cruz as the loss was not due to his fault or negligence.\nB)  No, Jose is not liable to Cruz. In the absence of any prohibition, Jose could lend the car to\nJolie. Since the loss was due to force majeure, neither Jose nor Jolie is liable.\nC)  Yes, Jose is liable to Cruz. Since Jose lent the car to Jolie without Cruz's consent, Jose must bear the consequent loss of the car.\nD) Yes, Jose is liable to Cruz. The contract between them is personal in nature. Jose can neither lend nor lease the car to a third person.\n\nSUGGESTED ANSWER:\n\nD. Commodatum is purely personal in nature, hence the bailee can neither lend nor lease the object of the contract to a third person.\n\n"
  },
  {
    "questionId": "6",
    "text": "6.   Sarah had a deposit in a savings account with Filipino Universal Bank in the amount of five Million pesos (P5,000,000.00). To buy a new car, she obtained a loan from the same bank in the amount of P1,200,000.00, payable in twelve monthly installments. Sarah issued in favor of the bank in post- dated checks, each in the amount of P100,000.00 to cover the twelve monthly installment payments. On the third, fourth and fifth months, the corresponding checks bounced.\n\nThe bank then declared the whole obligation due, and proceed to deduct the amount of one million pesos (P1,000,000.00) from Sarah's deposit after notice to her that this is a form of compensation allowed by law. Is the bank correct? Explain. (2009 BAR)\n\nSUGGESTED ANSWER:\n\nNo the bank is not correct, while the Bank is correct about the applicability of compensation, it was not correct as to the amount compensated.\n\nA bank deposit is a contract of loan, where the depositor is the creditor and the bank the debtor. Since Sarah is also the debtor of the bank with respect to the loan, both are mutually principal debtors and creditors of each other. Both obligations are due, demandable and liquidated but only up to the extent of P300,000 (covering the unpaid third, fourth and fifth monthly installments). The entire one million was not yet due because the loan has no acceleration clause in case of default. And since there is no retention or controversy commenced by third persons and communicated in due time to the debtor, then all the requisites of legal compensation are present but only up to the amount of P300,000. The bank, therefore, may deduct P300,000 pesos from Sarah's bank deposit by way of compensation.\n\n"
  },
  {
    "questionId": "7",
    "text": "7.   Felipe borrowed $100 from Gustavo in 1998, when the Phil P - US$ exchange rate was P56 - US$1.\nOn March 1, 2008, Felipe tendered to Gustavo a cashier’s check in the amount of P4,135 in payment\nof his US$100 debt, based on the Phil P - US$ exchange rate at that time. Gustavo accepted the check, but forgot to deposit it until Sept. 12, 2008. His bank refused to accept the check because it had become stale. Gustavo now wants Felipe to pay him in cash the amount of P5,600. Claiming that the previous payment was not in legal tender, and that there has been extraordinary deflation since 1998, and therefore, Felipe should pay him the value of the debt at the time it was incurred. Felipe refused to pay him again, claiming that Gustavo is estopped from raising the issue of legal tender, having accepted the  check in  March, and  that  it  was  Gustavo’s negligence in  not depositing the check immediately that caused the check to become stale. (2008 BAR)\n\nA)  Can Gustavo now raise the issue that the cashier’s check is not legal tender?\nB)  Can Felipe validly refuse to pay Gustavo again?\nC)  Can Felipe compel Gustavo to receive US$100 instead?\n\nSUGGESTED ANSWER:\n\nA) No, because Gustavo is guilty of estoppel by laches. He led Felipe to believe he could pay by cashier’s check, and Felipe relied that it would be encashed thus extinguishing his obligation. Because of Gustavo’s inaction of more than six months the check became stale and Felipe will be prejudiced if required to pay at the exchange rate of P56 to $ 1.00. The exchange should be the rate at the time of payment.\n\nALTERNATIVE ANSWER:\n\nA) Yes. The cashier’s check is not legal tender until it is encashed. (Art. 1249,CC). the cashier’s check by\nitself is not legal tender.\n\nSUGGESTED ANSWER:\n\nB) Yes, if the payment is valid. Since the bank considered the cashier’s check as being stale for not having been encashed on time, then the cashier’s check may be issued again. At any rate, non-payment of the amount to Gustavo would constitute unjust enrichment.\n\nSUGGESTED ANSWER:\n\nC) Yes. Felipe can compel Gustavo to pay US $100 instead. Under the prior law, RA 529, as amended by R.A. 4100, payment can only be in Philippine currency as it would be against public policy, null and void and of no effect. However, under RA 8183, payment maybe made in the currency agreed upon by the parties, and the rate of exchange to be followed is at the time of payment.\n\n"
  },
  {
    "questionId": "8",
    "text": "8.   Multiple choice: Choose the right answer. (2007 Bar Question) The parties to a bailment are the:\nA)  bailor; B)  bailee;\nC)  comodatario;\nD) all of the above;\nE)  letters a and b\n\nSUGGESTED ANSWER:\n\nE (letters A & B)\n\nALTERNATIVE ANSWER:\n\nD (all of the above)\n\nB.Deposit\n\n"
  },
  {
    "questionId": "9",
    "text": "9.   Due to the continuous heavy rainfall, the major streets in Manila became flooded. This compelled Cris to check-in at Square One Hotel. As soon as Crisgot off from his Toyota Altis, the Hotel’s parking attendant got the key of his car and gave him a valet parking customer’s claim stub. The attendant parked his car at the basement of the hotel. Early in the morning, Cris was informed by the hotel manager that his car was carnapped. (2014 BAR)\n\nA)  What contract, if any, was perfected between Cris and the Hotel when Cris surrendered the\nkey of his car to the Hotel’s parking attendant?\nB)  What is the liability, if any, of the Hotel for the loss of Cris’ car?\n\nSUGGESTED ANSWERS:\n\nA) The contract between Cris and Square One Hotel is one of necessary deposit. Deposit of effects made by travelers or guests in hotels or inns is considered a necessary deposit which includes personal effects brought inside the hotel premises as well as vehicles or animals and articles which have been introduced or placed in the annexes of the hotel.\n\nB) In Durban Apartments v. Pioneer Insurance (G.R. No. 179419 January 12, 2011), the Supreme Court held the hotel liable for the loss of the vehicle of the guest after its valet parking attendant parked the vehicle in front of a bank near the hotel premises. The court ruled that the bank’s parking area became an annex of the hotel when the management of the bank allowed the hotel to park vehicles there on the night in question. The contract of deposit was perfected when the guest surrendered the keys to his vehicle to the parking attendant. Ultimately, Square One Hotel is liable for the loss of the vehicle.\n\n"
  },
  {
    "questionId": "10",
    "text": "10.  Who enjoys the Right of Retention? (2014 BAR)\nA)  Depositary until full payment of what may be due him in deposit.\nB)  Lessee if he advances the expenses for the repair of the leased premises. C)  Bailee if bailor owes him something.\nD) Builder in bad faith for the recovery of necessary and useful expenses.\n\nSUGGESTED ANSWER: A.\n\n"
  },
  {
    "questionId": "11",
    "text": "11.  A deposit made in compliance with a legal obligation is: (2007 BAR) A)  an extrajudicial deposit\nB)  a voluntary deposit\n\nC)  a necessary deposit\nD) a deposit with a warehouseman\nE)  letters a and b\n\nSUGGESTED ANSWER: C\n\nC.Guaranty and Suretyship\n\n"
  },
  {
    "questionId": "12",
    "text": "12.  Kevin signed a loan agreement with ABC Bank. To secure payment, Kevin requested his girlfriend Rosella to execute a document entitled “Continuing Guaranty Agreement” whereby she expressly agreed to be solidarily liable for the obligation of Kevin.\n\nCan ABC Bank proceed directly against Rosella upon Kevin’s default even without proceeding\nagainst Kevin first? Explain your answer. (2017 BAR)\n\nSUGGESTED ANSWER:\n\nYes. Despite the designation of the contract as a “Continuing Guaranty Agreement,” the terms of the document prevail. Rosella expressly agreed to be solidarily liable for obligation of Kevin. If a person binds himself solidarily with the principal debtor, the contract is called a suretyship. A surety is under a direct and primary obligation to the creditor and may be proceeded against in case the principal debtor does not pay as he is an insurer of the debt. Only a guarantor enjoys the benefit of excussion.\n\n[Note:  It is the panel’s recommendation that due credit should also be given to examinees who answered that suretyship being an accessory contract, the principal debtor should be an indispensable party to the action against the surety].\n\n"
  },
  {
    "questionId": "13",
    "text": "13.  Define, enumerate or explain the difference between “guaranty” and “suretyship”?\n\nSUGGESTED ANSWER:\n\nGuaranty and Suretyship distinguished:\n●    The obligation in guaranty is secondary; whereas,in suretyship,it is primary.\n●\tIn guaranty, the undertaking is to pay if the principal debtor cannot pay;whereas, in suretyship, the undertaking is to pay if the principal debtor does\nnot pay.\n●\tIn guaranty, the guarantor is entitled to the benefit of excussion; whereas, in suretyship the surety is not so entitled.\n●\tLiability in guaranty depends upon an independent agreement to pay the obligations of the principal if he fails to do so; whereas, in suretyship, the\nsurety assumes liability as a regular party.\n●\tThe Guarantor insures the solvency of the principal debtor; whereas, the surety insures the debt.\n●    In a guaranty, the guarantor is subsidiarily liable; whereas, in a Suretyship,\nthe surety binds himself solidarily with the principal debtor. (Art. 2047, Civil Code)\n\n"
  },
  {
    "questionId": "14",
    "text": "14.  TRUE or FALSE. Explain your answer in not more than two (2) sentences.\nAn oral promise of guaranty is valid and binding. (2009 BAR)\n\nSUGGESTED ANSWER:\n\nFALSE. An oral contract of guaranty, being a special promise to answer for the debt of another, is unenforceable unless in writing (Article 1403[2] b, NCC).\n\nALTERNATIVE ANSWER:\n\nTRUE. An oral promise of guaranty is valid and binding. However, it is unenforceable because it is not in writing. Being a special promise to answer for the debt, default, or miscarriage of another, the Statute of Frauds requires it to be in writing to be enforceable (Article 1403 [2] b, NCC). The validity of a contract should be distinguished from its enforceability.\n\nD.   Antichresis\n\nE.Real estate mortgage\n\n"
  },
  {
    "questionId": "15",
    "text": "15.  Ellen entrusted her title over the lot where she is residing to Patrick, her nephew, for safekeeping because of her poor eyesight. Patrick, a gambler, prepared a Special Power of Attorney empowering him to mortgage the lot. Ellen’s signature was forged. With the help of Julia who represented herself as Ellen; Mega Bank granted a loan to Patrick secured by a mortgage on Ellen’s lot. Due to non-payment, Mega Bank foreclosed the mortgage and was declared the highest bidder. Title was later registered in the name of the bank. When Ellen was notified that she should vacate the premises, she filed a complaint to nullify the loan with mortgage, the auction sale and the title of Mega Bank on the ground that the bank is not a mortgagee in good faith. Decide the case with reasons. (2016 BAR)\n\nSUGGESTED ANSWER:\n\nI will decide in favor of Ellen. Banks, their business being impressed with public interest, are expected to exercise more care and prudence than private individuals in their dealings, even those involving registered lands. The highest degree of diligence is expected, and high standards of integrity and performance are even required of it.\n\nA mortgagee – usually, can rely on what appears on the certificate of title presented by the mortgagor and an innocent mortgagee is not expected to conduct an exhaustive investigation on the history of the mortgagor’s title. This rule is, however, strictly applied against banking institutions. Mega Bank cannot be considered a mortgagee in good faith as it failed to inspect the disputed property when offered to it as security for the loan, which could have led it to discover the forged Special Power of Attorney.\n\nALTERNATIVE ANSWER:\n\nI will decide in favor of Ellen, the victim of a forged document, Section 52 of P.D. No. 1529 provides that after the entry of a decree of registration, any subsequent registration procured by a forged deed shall be null and void, even if accompanied by the owner’s duplicate certificate of title. In this case, the registered owner, Ellen, did not lose her title, and neither did the mortgagee, Mega Bank, acquire any right to the property. The bank was defrauded because it believed the imposter who had, without authority, gained possession of Ellen’s certificate of title, and who then forged her signature to the deed of mortgage. It is not a mortgagee in good faith.\n\n"
  },
  {
    "questionId": "16",
    "text": "16.   Macario bought a titled lot from Ramon, got the title and took possession of the lot. Since Macario did not have the money to pay the taxes, fees and registration expenses, he was not able to register the Deed of Absolute Sale. Upon advice, he merely executed an Affidavit of Adverse Claim and had it annotated at the back of the title. A few years after, he received a Notice of Levy on Attachment and Writ of Execution in favor of Alex. The notice, writ and certificate of sale were annotated at the back of the title still in Ramon’s name. Alex contends that since the Affidavit of Adverse Claim is effective only for 30 days from the date of its registration, then its validity has expired. Macario posits that the annotation of his adverse claim is notice to the whole world of his\n\npurchase of the lot in question. Who has the superior right over the disputed property–Macario or\nAlex? Explain. (2016 BAR)\n\nSUGGESTED ANSWER:\nMacario is preferred since the registration of his adverse claim was made ahead of the notice of levy and writ of execution in favor of Alex. Coupled with the fact that he was in possession of the disputed property, it should have put Alex on constructive notice that the property had already been sold to another. The contention that the adverse claim is effective only for 30 years is puerile. In Sajonas v. Court of Appeals (G.R. No. 102377, July 5, 1996, 258 SCRA 79), the Court held that the adverse claim does not ipso facto lose its validity since an independent action is still necessary to render it ineffective. Until then, the adverse claim shall continue as a prior lien on the property.\n\n"
  },
  {
    "questionId": "17",
    "text": "17.  Mr. Bong owns several properties in Pasig City. He decided to build a condominium named Flores de Manila in one of his lots. To fund the project, he obtained a loan from the National Bank (NB) secured by a real estate mortgage over the adjoining property which he also owned. During construction, he  built  three  (3)  pumps  on  the  mortgaged property to  supply  water  to  the condominium. After one (1) year, the project was completed and the condominium was turned over to the buyers. However, Mr. Bong failed to pay his loan obligation to NB. Thus, NB foreclosed the mortgaged property where the pumps were installed. During the sale on public auction of the mortgaged property, Mr. Simon won in the bidding. When Mr. Simon attempted to take possession of the property, the condominium owners, who in the meantime constituted themselves into Flores de Manila Inc. (FMI), claimed that they have earlier filed a case for the declaration of the existence of an easement before the Regional Trial Court (RTC) of Pasig City and prayed that the easement be annotated in the title of the property foreclosed by NB. FMI further claimed that when Mr. Bong installed the pumps in his adjoining property, a voluntary easement was constituted in favor of FMI. Will the action prosper? (2014 BAR)\n\nSUGGESTED ANSWER:\n\nNO, the action will not prosper. The essence of a mortgage is that it immediately subjects the property upon which it is imposed, and the possesso, to the fulfillment of the obligation for whose security it was constituted (Art. 2126).\n\nThere was no voluntary easement in this case because at the time the water pumps were constructed, the subject lot where the water pumps were constructed and the condominium belong to the same person. No one can have an easement over his own property. Even of the assumption that an easement was created in favor of FMI, that alone will not defeat the right of the mortgagee to enforce the security if the debtor defaults.\n\n"
  },
  {
    "questionId": "18",
    "text": "18.  DMP Corporation (DMP) obtained a loan of P20 M from National Bank (NB) secured by a real estate mortgage over a 63,380-square meter land situated in Cabanatuan City. Due to the Asian Economic Crisis, DMP experienced liquidity problems disenabling it from paying its loan on time. For that reason, NB sought the extrajudicial foreclosure of the said mortgage by filing a petition for sale on June 30, 2003. On September 4, 2003, the mortgaged property was sold at public auction, which was eventually awarded to NB as the highest bidder. That same day, the Sheriff executed a Certificate of Sale in favor of NB.\n\nOn October 21, 2003, DMP filed a Petition for Rehabilitation before the RTC. Pursuant to this, a Stay Order was issued by the RTC on October 27, 2003.   On the other hand, NB caused the recording of the Sheriff’s certificate of Sale on December 3, 2003 with the Register of Deeds of Cabanatuan City. NB executed an Affidavit of Consolidation of Ownership and had the same annotated on the title of DMP.  Consequently, the Register of Deeds cancelled DMP’s title and issued a new title in the name of NB on December 10, 2003.  NB also filed on March 17, 2004 an Ex-Parte Petition for Issuance of Writ of Possession before the RTC of Cabanatuan City. After\n\nhearing, the RTC issued on September 6, 2004 an Order directing the Issuance of the Writ of\nPossession, which was issued on October 4, 2004.\n\nDMP claims that all subsequent actions pertaining to the Cabanatuan property should have been held in abeyance after the Stay Order was issued by the rehabilitation court. Is DMP correct? (2014\nBAR)\n\nSUGGESTED ANSWER:\n\nNo. DMP is not correct. Since the foreclosure of the mortgage and the issuance of the certificate of sale in favor of the mortgagee were done prior to the appointment of a Rehabilitation Receiver and the issuance of the Stay Order, all the actions taken with respect to the foreclosed mortgaged property which were subsequent to the issuance of the Stay Order were not affected by the Stay Order. Thus, after the redemption period expired without the mortgagor redeeming the foreclosed property, the mortgagee becomes the absolute owner of the property and it was within its right to ask for consolidation of title and the issuance of new title in its favor. The writ of possession procured by the mortgagee despite the subsequent issuance of Stay Order in the rehabilitation proceeding instituted is also valid.\n\n"
  },
  {
    "questionId": "19",
    "text": "19.  Lito obtained a loan of P1,000,000 from Ferdie, payable within one year. To secure payment, Lito executed a chattel mortgage on a Toyota Avanza and a real estate mortgage on a 200-square meter piece of property. (2013 BAR)\n\nA)  Would it be legally significant from the point of view of validity and enforceability, if the loan and the mortgages were in public or private instruments?\nB)  Lito's failure to pay led to the extra-judicial foreclosure of the mortgaged real property. Within a year from foreclosure, Lito tendered a manager's check to Ferdie to redeem the property. Ferdie refused to accept payment on the ground that he wanted payment in cash: the check does not qualify as legal tender and does not include the interest payment. Is Ferdie's refusal justified?\n\n"
  },
  {
    "questionId": "20",
    "text": "20.  Amador obtained a loan of P300,000 from Basilio payable on March25, 2012. As security for the payment of his loan, Amador constituted a mortgage on his residential house and lot in Basilio's favor. Cacho, a good friend of Amador, guaranteed and obligated himself to pay Basilio, in case Amador fails to pay his loan at maturity. (2013 BAR)\n\n1)   If Amador fails to pay Basilio his loan on March 25, 2012, can Basilio compel Cacho to pay? A)   No, Basilio cannot compel Cacho to pay because as guarantor, Cacho can invoke the principle\nof excussion, i.e., all the assets of Basilio must first be exhausted.\nB)  No, Basilio cannot compel Cacho to pay because Basilio has not exhausted the available remedies against Amador.\nC)  Yes, Basilio can compel Cacho to pay because the nature of Cacho's undertaking indicates\nthat he has bound himself solidarily with Amador.\nD) Yes, Basilio can compel Cacho who bound himself to unconditionally pay in case Amador fails to pay; thus the benefit of excussion will not apply.\n\n"
  },
  {
    "questionId": "21",
    "text": "21.  Does the right to request for the issuance of a writ of possession over a foreclosed real property prescribe in five (5) years? (2012 BAR)\n\nSUGGESTED ANSWER:\n\nNO, the purchaser’s right to request for the issuance of the writ of possession of the land never prescribes. The right to possess a property merely follows the right of ownership, and it would be illogical to hold that a person having ownership of a parcel of land is barred from seeking possession thereof.\n\n"
  },
  {
    "questionId": "22",
    "text": "22. X obtained a P10 M loan from BBB Banking Corporation. The loan is secured by REM on his vacation house in Tagaytay City. The original Deed of REM for the P10 M was duly registered. The Deed of REM also provides that “The mortgagor also agrees that this mortgage will secure the payment of additional loans or credit accommodations that may be granted by the mortgagee...” Subsequently, because he needed more funds, he obtained another P5 M loan. On due dates of both loans, X failed to pay the P5 M but fully paid the P10 M. BBB Banking Corporation instituted extrajudicial foreclosure proceedings. (2012 BAR)\n\nA)  Will the extrajudicial foreclosure prosper considering that the additional P5 M was not covered by the registration?\nB)  What is the meaning of a “dragnet clause” in a Deed of Real Estate Mortgage? Under what\ncircumstances will be “dragnet clause” applicable?\n\n"
  },
  {
    "questionId": "23",
    "text": "23. X defaulted in his loan with Y. Y instituted extra-judicial foreclosure of the property subject to a real estate mortgage that secured the loan. X has 1 year within which to redeem the property. After\n\nthe foreclosure, X filed an action questioning the validity of the extra-judicial foreclosure sale. Which statement is most accurate? (2012 BAR)\n\nA)  The 1 year period within which to redeem will be interrupted by the filing of an action questioning the validity of the foreclosure;\nB)  The 1 year period will not be interrupted by the filing of the action;\nC)  The   1   year   period   will   be   extended   for   another   year   because   of   the   filing of an action questioning the validity of the foreclosure sale;\nD) If     the     action     which     questions     the     validity     of     the     foreclosure    prospers, the period will be interrupted.\n\nSUGGESTED ANSWER: B\n\n"
  },
  {
    "questionId": "24",
    "text": "24. What is the effect if the proceeds in an extra-judicial foreclosure sale is not sufficient to pay for the obligation? (2012 BAR)\n\nA)  The mortgagee can claim for deficiency judgment from the debtor;\nB)  The     mortgagee     can     claim     for     deficiency     judgment     from     the     mortgagor even though it is a third party mortgage;\nC)  The mortgagee has no more recourse or claim against the debtor;\nD) The     mortgagee     cannot     claim     for     deficiency     judgment     from     the     debtor\nbecause it’s an extrajudicial foreclosure.\n\nSUGGESTED ANSWER: A\n\n"
  },
  {
    "questionId": "25",
    "text": "25. X mortgaged her residential house and lot in favor of ABC Bank. X defaulted in her loan and so the bank foreclosed the real estate mortgage on the residential house. Y then bought the residential house and lot before the expiration of the redemption period. Can Y now take possession of the property? (2012 BAR)\n\nA)  No, because it is still covered by the redemption period and the purchaser is not yet entitled as a matter of right to take possession of the property;\nB)  Yes, the purchaser is now entitled to the possession of the house; C)  No, because there is a need to talk to X to leave the house;\nD) No, because Y was not the one who foreclosed the mortgage on the property. SUGGESTED ANSWER: A\n"
  },
  {
    "questionId": "26",
    "text": "26. Which phrase best completes the statement—When a debt is secured by a real estate mortgage,\nupon default of the debtor: (2012 BAR)\nA)  The only remedy of the creditor is to foreclose the real estate mortgage;\nB)  Another    remedy    is    filing    an    action    for    collection    and    then    foreclose    if collection is not enough;\nC)  The    creditor    can    foreclose    the    mortgage    and    demand    collection    for    any\ndeficiency;\nD) None of the above.\n\nSUGGESTED ANSWER: C\n\n"
  },
  {
    "questionId": "27",
    "text": "27. X obtained a loan for P50 M from SSS Bank. The collateral is his vacation house in Baguio City under a real estate mortgage. X needed more funds for his business so he again borrowed another P10 M, this time from BBB Bank, another bank, using the same collateral. The loan secured from SSS Bank fell due and X defaulted. (2012 BAR)\n\nA)  If SSS Bank forecloses the real estate mortgage, what rights, if any, are left with BBB Bank as mortgagee also?\nB)  If the value of the Baguio property is less than the amount of loan, what would be the recourse of SSS bank? BBB Bank?\nC)  If the value of the property is more that the amount of the loan, who will benefit from the excess value of the property?\nD) If X defaulted with its loan in favor of BBB Bank but fully paid his loan with SSS Bank, can\nBBB foreclose the real mortgage executed in its favor?\nE)  Does X have any legal remedy after the foreclosure in the event that later on he has the money to pay for the loan?\nF)  If SSS Bank and BBB Bank abandoned their rights under the real estate mortgage, is there any legal recourse available to them?\n\n"
  },
  {
    "questionId": "28",
    "text": "28. Asiong borrowed P1 million from a bank, secured by a mortgage on his land. Without his consent, his friend Boyong paid the whole loan. Since Asiong benefited from the payment, can Boyong compel the bank to subrogate him in its right as mortgagee of Asiong's land? (2011 BAR)\nA)  No, but the bank can foreclose and pay Boyong back.\nB)  No, since Boyong paid for Asiong’s loan without his approval.\nC)  Yes, since a change of creditor took place by novation with the bank’s consent.\nD) Yes, since it is but right that Boyong be able to get back his money and, if not, to foreclose the mortgage in the manner of the bank.\n\nSUGGESTED ANSWER: B\n\n"
  },
  {
    "questionId": "29",
    "text": "29. The right of a mortgagor in a judicial foreclosure to redeem the mortgaged property after his default in the performance of the conditions of the mortgage but before the sale of the mortgaged property or confirmation of the sale by the court, is known as: (2011 BAR)\nA)  accion publiciana.\nB)  equity of redemption. C)  pacto de retro.\nD) right of redemption. SUGGESTED ANSWER: B\n\n"
  },
  {
    "questionId": "30",
    "text": "30. X, at Y’s request, executed a Real Estate Mortgage (REM) on his (X’s) land to secure Y’s loan from Z. Z successfully foreclosed the REM when Y defaulted on the loan but half of Y’s obligation remained unpaid. May Z sue X to enforce his right to the deficiency? (2011 BAR)\nA)  Yes, but solidarily with Y.\nB)  Yes,    since    X’s    is    deemed    to    warrant    that    his    land    would    cover    the\nwhole obligation.\nC)  No,    since    it    is    the    buyer    at    the    auction    sale    who    should    answer    for the deficiency.\nD) No, because X is not Z’s debtor.\n\nSUGGESTED ANSWER: D\n\n"
  },
  {
    "questionId": "31",
    "text": "31.  On X’s failure to pay his loan to ABC Bank, the latter foreclosed the Real Estate Mortgage he executed in its favor. The auction sale was set for Dec. 1, 2010 with the notices of sale published as the law required. The sale was, however, cancelled when Dec. 1, 2010 was declared a holiday and rescheduled to Jan. 10, 2011 without republication of notice. The auction sale then proceeded on the new date. Under the circumstance, the auction sale is: (2011 BAR)\nA)  Rescissible.\nB)  Unenforceable. C)  Void.\nD) Voidable. SUGGESTED ANSWER: C\n"
  },
  {
    "questionId": "32",
    "text": "32. Ozamis Paper Corporation secured loans from ABC Universal Bank in the aggregate principal amount of P100 M, evidenced by several promissory notes, and secured by a continuing guaranty of its principal stockholder Menandro Marquez; a pledge of Marquez’s shares in the corporation valued at P45 M; and a real estate mortgage over certain parcels of land owned by Marquez.\n\nThe corporation defaulted and the bank extra-judicially foreclosed on the real estate mortgage. The bank, which was the sole bidder for P75 M, won the award. (2010 BAR)\n\n\n\nA)  Can the bank sue Marquez for the deficiency of P25 M? Explain.\nB)  If the bank opts to file an action for collection against the corporation, can it afterwards institute a real action to foreclose the mortgage? Explain.\nC)  Can the bank foreclose on the pledged shares of Marquez and recover the deficiency from the corporation?\n\nSUGGESTED ANSWERS:\n\nA)  Yes, the bank can sue Marquez for the deficiency of P25 M. in extrajudicial foreclosure of a real estate mortgage, if the proceeds of the sale are insufficient to pay the debt, the mortgagee has the right to sue for the deficiency.\n\nB)  No, the bank can no longer file an action to foreclose the real estate mortgage. When it filed a collection case, it was deemed to have abandoned the real estate mortgage.\n\nC)  If the bank forecloses the pledge, it cannot recover the deficiency because the foreclosure extinguishes the principal obligation, whether or not the proceeds from the foreclosure are equal to the amount of the principal obligation.\n\n"
  },
  {
    "questionId": "33",
    "text": "33. Eduardo was granted a loan by XYZ Bank for the purpose of improving a building which XYZ\nleased from him. Eduardo, executed the promissory note (“PN”) in favor of the bank, with his\n\nfriend Recardo as cosignatory. In the PN, they both acknowledged that they are “individually and collectively” liable and waived the need for prior demand. To secure the PN, Recardo executed a real estate mortgage on his own property. When Eduardo defaulted on the PN, XYZ stopped payment of rentals on the building on the ground that legal compensation had set in. Since there was still a balance due on the PN after applying the rentals, XYZ foreclosed the real estate mortgage over Recardo’s property.\n\nRecardo opposed the foreclosure on the ground that he is only a co-signatory; that no demand was made upon him for payment, and assuming he is liable, his liability should not go beyond half the balance of the loan. Further, Recardo said that when the bank invoked compensation between the rentals and the amount of the loan, it amounted to a new contract or novation, and had the effect of extinguishing the security since he did not give his consent (as owner of the property under the real estate mortgage) thereto.\n\nxxx\n\nCan Recardo’s property be foreclosed to pay the full balance of the loan? (2008 BAR)"
  },
  {
    "questionId": "34",
    "text": "34. Industry Bank, which has a net worth of P1 Billion, extended a loan to celestial Properties Inc. amounting to P270 M. the loan was secured by a mortgage over a vast commercial lot in the Fort Bonifacio Global City, appraised at P350 M. After audit, the BSP gave notice that the loan to Celestial Properties exceeded the single borrower’s limit of 25% of the bank’s net worth under a recent BSP Circular. In light of other previous similar violations of the credit limit requirement, the BSP advised Industry Bank to reduce the amount of the loan to Celestial Properties under pain of severe sanctions. When Industry Bank informed Celestial Properties that it intended to reduce the loan by P50 M, Celestial Properties counter-proposal, and referred the matter to you as counsel. How would you advise Industry Bank to proceed, with its best interest in mind? (2008 BAR)\n\n\nSUGGESTED ANSWER:\n\nI shall advise Industry Bank that the mortgage is indivisible. Therefore, Celestial Properties cannot ask for a partial release of the mortgage so long as the loan has not been completely paid.\n\n"
  },
  {
    "questionId": "35",
    "text": "35. On December 4, 2003, RED Corporation executed a real estate mortgage in favor of BLUE Bank.\nRED Corporation defaulted in the payment of its loan. Consequently, on June 4, 2004, BLUE Bank\nextrajudicially foreclosed the property. Being the highest bidder in the auction sale conducted, the Bank was issued a Certificate of Sale which was registered on August 4, 2004. Does RED Corporation still have the right to redeem the property as of September 14, 2007? Reason briefly. (2007 BAR)\n\n"
  }
];