const questions = [
  {
    "questionId": 1,
    "text": "\n1.\tTRUE OR FALSE. Possession of a movable property is lost when the location of the said movable is unknown to the owner. (2017 BAR)\n\n\nArticle 556 of the Civil Code provides that the possession of movables is not deemed lost so long as they remain under the control of the possessor, even though for the time being he may not know their whereabouts. Possession of a movable, therefore, is lost only when possessor loses control over it.\n\n"
  },
  {
    "questionId": 2,
    "text": "2.   On February 28, 1998, Arthur filed an application for registration of title of a lot in Ternate, Cavite before the Regional Trial Court of Naic, Cavite under Section 48(6) of Commonwealth Act No. 141 (CA 141) for judicial confirmation of imperfect title. Section 48(b) of CA 147 requires possession counted from June 12, 1945. Arthur presented testimonial and documentary evidence that his possession and that of his predecessors-in interest started in 1936. The lot was declared alienable and disposable (A and D) in 1993 based on a PENRO certification and a certified true copy of the original classification made by the DENR Secretary. The government opposed the application on the ground that the lot was certified A and D only in 1993 while the application was instituted only in 1998. Arthur’s possession of five (5) years from the date of declaration does not comply with the\n30-year period required under CA 141. Should the possession of Arthur be reckoned from the date when the lot was declared A and D or from the date of actual possession of the applicant? Explain.\n(5%) (2016 BAR)\n\n\n"
  },
  {
    "questionId": 3,
    "text": "3.   Which of the following statements is wrong? (2012 BAR)\nA)  patrimonial property of the state, when no longer intended for public use or for public service, shall become property of public dominion.\nB)  all property of the State, which is not of public dominion, is patrimonial property.\nC)  The property of provinces, cities and municipalities is divided into property for public use and patrimonial property.\nD) Property is either of public dominion or of private ownership.\n\nSUGGESTED ANSWER: A\n\n"
  },
  {
    "questionId": 4,
    "text": "4.   Manila Petroleum Co. owned and operated a petroleum operation facility off the coast of Manila.\nThe facility was located on a floating platform made of wood and metal, upon which was permanently attached the heavy equipment for the petroleum operations and living quarters of the crew. The floating platform likewise contained a garden area, where trees, plants and flowers were planted. The platform was tethered to a ship, the MV 101, which was anchored to the seabed.\n\nIs the platform movable or immovable property? (2007BAR) SUGGESTED ANSWER:\nThe platform is an immovable property under Article 415 (9), NCC which provides that “docks and structures which, though floating, are intended by their nature and object to remain at a fixed place on a river, lake or coast.” Since the floating platform is a petroleum operation facility, it is intended to remain permanently where it is situated, even if it is tethered to a ship which is anchored to the seabed.\n\nALTERNATIVE ANSWER:\n\nThe platform is a movable property because it is attached to a movable property, i.e. the vessel which was merely anchored to the seabed. The fact that the vessel is merely anchored to the seabed only shows that it is not intended to remain at a fixed place; hence, it remains a movable property. If the intention was to make the platform stay permanently where it was moored, it would not have, been simply tethered to a vessel but itself anchored to the seabed.\n\n"
  },
  {
    "questionId": 5,
    "text": "5.   Are the equipment and living quarters movable or immovable property? (2007 BAR) SUGGESTED ANSWER:\nThe equipment and living quarters of the crew are immovable property under Article 415 (3) NCC, classifies\nas an immovable “everything attached to an immovable in a fixed manner, in such a way that it cannot be\nseparated therefrom without breaking the material or deterioration of the object”. Both the equipment and the living quarters are permanently attached to the platform which is also an immovable.The equipment can also be classified as an immovable property under Article 415 (5) NCC because such equipment are “machinery, receptacles, instruments or implements intended by the owner of the tenement for an industry or works which may be carried on in a building or on a piece of land and which tend directly to meet the\n\nneeds of the said industry or works”. It is logically, assumed that the petroleum industry may be carried on' in a building or on a piece of land and the platform is analogous to a building.\n\nALTERNATIVE ANSWER:\n\nThe equipment and living quarters of the crew are movable properties since they are attached to a platform which is also movable property, because it is simply attached to a vessel is likewise a movable property since it was merely anchored to the seabed. The fact that the vessel is merely anchored on the sea- bed only shows that it is not intended to remain at a fixed place; hence, it remains a movable property.\n\n"
  },
  {
    "questionId": 6,
    "text": "6.   Are the trees, plants and flowers immovable or movable property? Please briefly give the reason for your answers. (2007 BAR)\n\nSUGGESTED ANSWER:\n\nThe trees, plants and flowers planted in the garden area of the platform are immovable property under Article 415 (2) NCC which classifies as an immovable property “trees, plants and growing fruits, while they are attached to the land or form an integral part of an immovable.” The garden forms an integral part of an immovable, the petroleum operation facility.\n\nALTERNATIVE ANSWER:\n\nThe trees, plants and flowers planted in the garden area of the platform are movable property because they are not permanently attached to the land and do not form an integral part of an immovable. The platform is not an immovable property for the same reason already given in the Alternative Answer to Item (a) above.\n\nB.Ownership\n\n"
  },
  {
    "questionId": 7,
    "text": "7.   In 1960, Rigor and Mike occupied two separate but adjacent tracts of land in Mindoro. Rigor’s tract was classified as timber land while Mike’s was classified as agricultural land. Each of them fenced and cultivated his own tract continuously for 30 years. In 1991, the Government declared the land occupied by Mike as alienable and disposable, and the one cultivated by Rigor as no longer intended for public use or public service.\n\nRigor and Mike now come to you today for legal advice in asserting their right of ownership of their respective lands based on their long possession and occupation since 1960. (2017 BAR)\n\nA)  What are the legal consequences of the 1991 declarations of the Government respecting the lands? Explain your answer.\nB)  Given that, according to Section 48(b) of Commonwealth Act No. 141, in relation to Section\n14(1)  of  Presidential  Decree  No.  1529,  the  open,  continuous,  exclusive,  and  notorious\npossession and occupation of alienable and disposable lands of the public domain as basis for judicial confirmation of imperfect title must be from June 12, 1945, or earlier, may Mike nevertheless validly base his assertion of the right of ownership on prescription under the Civil Code? Explain your answer.\nC)  Does Rigor have legal basis for his application for judicial confirmation of imperfect title based on prescription as defined by the Civil Code given that, like Mike, his open, continuous, exclusive, and notorious possession and occupation was not since June 12, 1945, or earlier, and his tract of land was timber land until the declaration in 1991. Explain your answer.\n\n\n"
  },
  {
    "questionId": 8,
    "text": "8.   TRUE OR FALSE: All rights are considered as property. SUGGESTED ANSWER:\nFalse. Only right which are patrimonial in character can be considered property. Rights which are not patrimonial, such as the right to liberty, the right to honor, family rights, and political rights cannot be considered property.\n\n"
  },
  {
    "questionId": 9,
    "text": "9.   TRUE OR FALSE: A lessee cannot bring a case for quieting of title respecting the property that he leases.\n\nSUGGESTED ANSWER:\n\nTrue. The plaintiff must have a legal or equitable title to the real property in question or some interest therein, (or must be possession thereof, so that the action may be in prescriptible [Article 476-477, Civil Code].\n\nALTERNATIVE ANSWER:\n\nFalse. If the property lease is a moveable property, like a car, an airplane or a ship, the lessee cannot bring the action to quiet title.  The property - subject matter of the action to quiet title should be real property only [Art. 477, NCC].\n\n"
  },
  {
    "questionId": 10,
    "text": "10.  Plutarco owned land that borders on a river. After several years the action of the water of the river caused the deposit of soil, and increased the area of Plutarco’s property by 200 square meters. (2017 BAR)\nA)  If Plutarco wants to own the increase in area, what will be his legal basis for doing so? Explain\nyour answer.\nB)  On the other hand, if the river dries up, may Plutarco validly claim a right of ownership of the dried-up river bed? Explain your answer.\n\nSUGGESTED ANSWER:\n\nA)  Plutarco’s legal basis for owning the increase in area would be by accretion under Article 457 of the New Civil Code, which says that the accretion of soil which is gradually received from the effects of the current of the waters belongs to the owners of land adjoining the banks of the river. The requisites in order that the reparian owner will own the alluvion deposited through the process of accretion are as follows: (1). the deposit should be gradual and imperceptible, (2). the cause of the accretion is the current of the river and is not artificial or man-made, and 3) the land where the accretion takes place is adjacent to the river bank. In Plutarco’s case, all three requisites are met, as the accretion took place over several years, was caused by the action of the river, and the land he owned borderes a river; therefore, he owns the increase in area by virtue of accretion.\n\nB)  Rivers and their natural beds, being of public dominion [Article 502(1) Civil Code], are not subject to appropriation or accretion. The dried-up riverbed remains to be of public dominion and Plutarco cannot validly claim a right ownership over it [Republic v. Santos, G.R. No. 160453 (2012)].\n\n"
  },
  {
    "questionId": 11,
    "text": "11.  Benjamin is the owner of a titled lot which is bounded on the north by the Maragondon River. An alluvial deposit of two (2) hectares was added to the registered area. Daniel took possession of the portion formed by accretion and claims that he has been in open, continuous and undisturbed possession of said portion since 1923 as shown by a tax declaration. In 1958, Benjamin filed a complaint for Quieting of Title and contends that the alluvium belongs to him as the riparian owner and that since the alluvium is, by law, part and parcel of the registered property, the same may be considered as registered property, Decide the case and explain. (2016 BAR)\n\nSUGGESTED ANSWER:\n\nI will decide in favor of Daniel and dismiss the action to quiet title filed by Benjamin, Under Article 457 of the Civil Code, the owner of lands adjoining the banks of rivers belong the accretion which they gradually receive from the effects of the current of the waters. The accretion however, does not automatically become\n\nregistered land. It must be brought under the Torrens system of registration by Benjamin, the reparian owner. Since he did not, the then increment, not being registered land, was open to acqui sition through prescription by third persons, like Daniel (Grande v. Court of Appeals, G.R. No. L-17652, June 30, 1962,5\nSCRA 524; Cureg v. Intermediate Appellate Court, G.R. No, 73465, September 7, 1989, 177 SCRA 313).\n\n"
  },
  {
    "questionId": 12,
    "text": "12.  Mr. and Mrs. X migrated to the US with all their children. As they had no intention of coming back, they offered their house and lot for sale to their neighbors, Mr. and Mrs. A (the buyers) who agreed to buy the property for 128 Million. Because Mr. and Mrs. A needed to obtain a loan from a bank first, and since the sellers were in a hurry to migrate, the latter told the buyers that they could already occupy the house, renovate it as it was already in a state of disrepair, and pay only when their loan is approved and released. While waiting for the loan approval, the buyers spent .Pl Million in repairing the house. A month later, a person carrying an authenticated special power of attorney from the sellers demanded that the buyers either immediately pay for the property in full now or vacate it and pay damages for having made improvements on the property without a sale having been perfected.\n\nWhat are the buyers' options or legal rights with respect to the they expenses incurred in improving the property under circumstances? (2015 BAR)\n\nSUGGESTED ANSWER:\n\nThe buyers here may be deemed possessors or builders in good faith because they were made to believe that they were allowed to make repairs or renovation by the sellers themselves. As builders in good faith, they have the right to seek reimbursement for the value of the improvements in case the owner decides to appropriate them. They cannot be asked to remove the improvements because that is not one of the options given by law to the landowner in case the builder is in good faith.\n\n"
  },
  {
    "questionId": 13,
    "text": "13.  A congregation for religious women, by way of commodatum, is using the real property owned and registered in  the  name of  Spouses Manuel as  a  retreat house. Maria, a  helper of  the congregation discovered a chest in the backyard. When she opened the chest, it contained several pieces of jewelry and money. (2014 BAR)\nA)  Can the chest containing the pieces of jewelry and money be considered as hidden treasure?\nB)  Who has the right to claim ownership of it? SUGGESTED ANSWERS:\nA)  NO, for property to be considered hidden treasure it must consist of money, jewelry or other precious objects, the lawful ownership of which does not appear. In the case at bar, the chest was just lay in the backyard and the real property where it was found belongs to the Spouses Manuel. They are thus presumed the owner of the chest where the jewelry was found.\n\nB)  Since it does not come within the purview of hidden treasure, the spouses Manuel have the right to claim ownership over the chest as well as its contents.\n"
  },
  {
    "questionId": 14,
    "text": "14.  A delayed accession is: (2014 BAR) A)  formation of an island\nB)  avulsion\nC)  alluvium\nD) change in the course of the riverbed\n\nSUGGESTED ANSWER:\n\nB (Art. 459)\n\n\n"
  },
  {
    "questionId": 15,
    "text": "15.  Ciriaco Realty Corporation (CRC) sold to the spouses Del a Cruz a 500-square meter land (Lot A) in Paranaque. The land now has a fair market value of Pl,200,000. CRC likewise sold to the spouses Rodriguez, a 700-square meter land (Lot B) which is adjacent to Lot A. Lot B has a present fair market value of P1,500,000. The spouses Dela Cruz constructed a house on Lot B, relying on there presentation of the CRC sales agent that it is the property they purchased. Only upon the completion of their house did the spouses Dela Cruz discover that they had built on Lot B owned by the spouses Rodriguez, not on Lot A that they purchased. They spent P 1 000,000 for the house. As their lawyer, advise the spouses Dela Cruz on their rights and obligations under the given circumstances, and the recourses and options open to them to protect their interests. (2013 BAR)\n\nSUGGESTED ANSWER:\n\nBased on the facts as stated, the spouses Dela Cruz as builders and the spouses Rodriguez as landowners, are both in good faith. The spouses Dela Cruz are builders in good faith because before constructing the house they exercised due diligence by asking the agent of CRC the location of Lot A. and they relied on the information given by the agent who is presumed to know the identity of the lot purchased by the Dela Cruz spouses (Pleasantville v. CA, G.R. No. 79688, February 1, 1996). On the other hand, there is no showing that the landowners, spouses Rodriguez, acted in bad faith. The facts do not show that the building was done with their knowledge and without opposition on their part (Art. 453). Good faith is always presumed (Art. 527). The owner of the land on which anything has been built, sown or planted in good faith shall have the right: 1. to appropriate as his own the works after payment of the indemnity provided for in Articles 546 and 548, or 2. to oblige the one who built to pay the price of the land.\n\nHowever, the builder cannot be obliged to buy the land if its value is considerably more than that of the building. In such case, he shall pay reasonable rent if the owner of the land does not choose to appropriate the building or trees after proper indemnity (Art. 448).\n\nThe house constructed by the spouses Dela Cruz is considered as a useful expense, since it increased the value of the lot. As such, should the spouses Rodriguez decide to appropriate the house, the spouses Dela Cruz are entitled to the right of retention pending reimbursement of the expenses they incurred or the increase in value which the thing may have acquired by reason of the improvement (Art. 546). Thus, the spouses Dela Cruz may demand P1,000,000 as payment of the expenses in building the house or increase in value of the land because of the house as a useful improvement, as may be determined by the court front the evidence presented during the trial (Depra Dumlao, G.R. No. L 57348, May 16, 1985; Technogas Phils. v. CA, G.R. No. 108894, February 10, 1997).\n\n"
  },
  {
    "questionId": 16,
    "text": "16.  The owner of a thing cannot use it in a way that will injure the right of a third person. Thus, every building or land is subject to the easement which prohibits its proprietor or possessor from committing nuisance like noise, jarring, offensive odor, and smoke. This principle is known as (2011 BAR)\nA)  Jus vindicandi.\nB)  Sic utere tuo ut alienum non laedas. C)  Jus dispondendi.\nD) Jus abutendi. SUGGESTED ANSWER: B\n"
  },
  {
    "questionId": 17,
    "text": "17.  O, owner of Lot A, learning that Japanese soldiers may have buried gold and other treasures at the adjoining vacant Lot B belonging to spouses X & Y, excavated in Lot B where she succeeded in unearthing gold and precious stones. How will the treasures found by O be divided? (2010 BAR) A)  100% to O as finder\nB)  50% to O and 50% to the spouses X and Y C)  50% to O and 50% to the state\n\nD) None of the above\n\nSUGGESTED ANSWER:\n\nD\n\nThe general rule is that the treasure shall belong to the spouses X and Y, the owners of Lot B. Under Article 438 (NCC), the exception is that when the discovery of a hidden treasure is made on the property of another and by chance, one-half thereof shall belong to the owner of the land and the other one-half is allowed to the finder. In the problem, the finding of the treasure was not by chance because O knew that the treasure was in Lot B. While a trespasser is also not entitled to any share, and there is no indication in the problem whether or not O was a trespasser, O is not entitled to a share because the finding was not “by chance”\n\n"
  },
  {
    "questionId": 18,
    "text": "18.  Adam, a building contractor, was engaged by Bias to construct a house on a lot which he (Bias) owns. While digging on the lot in order to lay down the foundation of the house, Adam hit a very hard object. It turned out to be the vault of the old Banco de las Islas Filipinas. Using a detonation device, Adam was able to open the vault containing old notes and coins which were in circulation during the Spanish era. While the notes and coins are no longer legal tender, they were valued at P 100 million because of their historical value and the coins’ silver and nickel content. The following filed legal claims over the notes and coins: (2008 BAR)\n\ni.      Adam, as finder;\nii.      Blas, as owner of the property where they were found;\niii.      Bank of the Philippine Islands, as successor-in-interest of the owner of the vault; and iv.      The Philippine Government because of their historical value.\nv.      Who owns the notes and coins?\n\nSUGGESTED ANSWER:\n\nHidden treasure is money jewelry or other precious objects the ownership of which does not appear (Art.\n439, CC). The vault of the Banco de las Islas Filipinas has been buried for about a century and the Bank\nof the “Philippine Islands cannot succeed by inheritance to the property of Banco de las Islas Filipinas. The ownership of the vault, together with the notes and coins can now \"legally be considered as hidden treasure because its ownership is no longer apparent. The contractor, Adams is not a trespasser and therefore entitled to one-half of the hidden treasure and Bias as owner of the property, is entitled the other half (Art. 438, CC). Since the notes and , coins have historical value, the government may acquire them at their just price which in turn will be divided equally between Adam and Bias (Art. 438, par. 3, CC).\n\n"
  },
  {
    "questionId": 19,
    "text": "19.  Which of the following is an indispensable requirement in an action for \"quieting of title\" involving real property? The plaintiff must (2011 BAR)\nA)  be in actual possession of the property. B)  be the registered owner of the property.\nC)  have legal or equitable title to the property. D) be the beneficial owner of the property.\n\nSUGGESTED ANSWER: C\n\n\nC.Co-ownership\n\n"
  },
  {
    "questionId": 20,
    "text": "20. X, Y, Z are siblings who inherited a 10-storey building from their parents. They agreed in writing to maintain it as a co-owned property for leasing out and to divide the net profits among themselves equally for a period of 20 years. On the 8th year, X wanted to get out of the co- ownership so he could get his 1/3 share in the property. Y and Z refused, saying X is bound by their agreement to keep the co-ownership for 20 years. Are Y and Z correct? Explain. (2015 BAR)\n\nSUGGESTED ANSWER:\n\nY and Z are partly correct. The law provides that none of the co-owners shall be obliged to remain in the co-ownership and it is the right of a co-owner to ask for partition of the co-ownership anytime. One exception to the rule is if the co-owners agree to keep the thing undivided which period shall not exceed ten years. In this case, the agreement to keep the thing undivided shall be valid at the most for ten years (Art. 494).\n\n"
  },
  {
    "questionId": 21,
    "text": "21.  Raul, Ester, and Rufus inherited a 10-hectare land from their father. Before the land could be partitioned, however, Raul sold his hereditary right to Raffy, a stranger to the family, for P5 million. Do Ester and Rufus have a remedy for keeping the land within their family? (2011 BAR)\nA)  Yes, they may be subrogated to Raffy’s right by reimbursing to him within the required time\nwhat he paid Raul.\nB)  Yes, they may be subrogated to Raffy’s right provided they buy him out before he registers the\nsale.\nC)  No, they can be subrogated to Raffy’s right only with his conformity. D) No, since there was no impediment\n\nSUGGESTED ANSWER: A\n\n"
  },
  {
    "questionId": 22,
    "text": "22. Is the testamentary prohibition against the division of the London estate valid? (2008 BAR) SUGGESTED ANSWER:\nThe testamentary prohibition against the division by Peter and Paul of the London estate for as long as\nthey live, is not valid. Article 494 of the New Civil Code provides that a donor or testator may prohibit\npartition for a period which may not exceed twenty (20) years.\n\nD.   Possession\n\n"
  },
  {
    "questionId": 23,
    "text": "23. Jacob has owned a farm land in Ramos, Tarlac. In 2012, Liz surreptitiously entered and cultivated the property. In 2014, Jacob discovered Liz’s presence in and cultivation of the property. Due to his being busy attending to his business in Cebu, he tolerated Liz’s cultivation of the property. Subsequently, in December 2016, Jacob wanted to regain possession of the property; hence, he sent a letter to Liz demanding that she vacate the property. Liz did not vacate despite the demand. Jacob comes to enlist your legal assistance to bring an action against Liz to recover the possession of the property.What remedies are available to Jacob to recover possession of his property under the circumstances? Explain your answer. (2017 BAR)\n\n\nSUGGESTED ANSWER:\n\nThe remedy available to Jacob is accion publiciana, or an action for the recovery of the better right of possession or possession as a real right. It also refers to an ejectment suit filed after the expiration of one year from accrual of the cause of action or from the unlawful withholding of possession of the realty.\n\nSince the entry made by Liz is through stealth, Jacob could have filed an action for forcible entry. Ordinarily, the one-year period within which to bring an action for forcible entry is generally counted from the date of actual entry on the land, except that when the entry is through stealth, the one-year period is counted from the time the plaintiff learned thereof. Here, since more than one year had elapsed since Jacob learned of the entry made by Liz through stealth, the action that may be filed by Jacob is no longer forcible entry, but an accion publiciana [Canlas v. Tubil, G.R. No. 184285(2009); Valdez v. CA, G.R. No. 132424 (2006)].\n\n"
  },
  {
    "questionId": 24,
    "text": "24. Betty entrusted to her agent, Aida, several pieces of jewelry to be sold on commission with the express obligation to turn over to Betty the proceeds of the sale, or to return the jewelries if not sold in a month's time. Instead of selling the jewelries, Aida pawned them with the Tambunting Pawnshop, and used the money for herself. Aida failed to redeem the pawned jewelries and after a month, Betty discovered what Aida had done. Betty brought criminal charges which resulted in Aida's conviction for estafa.  Betty thereafter filed an action against Tambunting Pawnshop for the recovery of the jewelries. Tambunting raised the defense of ownership, additionally arguing that it is duly licensed to engage in the pawnshop and lending business, and that it accepted the mortgage of the jewelry in good faith and in the regular course of its business. If you were the judge, how will you decide the case? (2013 BAR)\n\nA)  I will rule in favor of Betty. My ruling is based on the Civil Code provision that one who has lost any movable or has been unlawfully deprived thereof may recover it from the person in possession of the same. Tam bunting's claim of good faith is inconsequential.\nB)  I will rule in favor of Betty. Tambunting's claim of good faith pales into insignificance in light of the unlawful deprivation of the jewelries. However, equity dictates that Tambunting must be reimbursed for the pawn value of the jewelries.\nC)  I will rule in favor of Tambunting. Its good faith takes precedence over the right of Betty to recover the jewelries.\nD)  I will rule in favor of Tambunting. Good faith is always presumed. Tambunting's lawful\nacquisition in the ordinary course of business coupled with good faith gives it legal right over the jewelries.\n\nSUGGESTED ANSWER:\n\nA. Article 559 of the Civil Code applies (See Dizon vs. Suntay 47 SCRA 160)\n\n"
  },
  {
    "questionId": 25,
    "text": "25. Which of the following statements is wrong? (2012 BAR)\n\nA)  The possessor in bad faith shall reimburse the fruits received and those which the legitimate possessor could have received.\nB)  The possessor in bad faith has right of reimbursement for necessary expenses and those for\nthe production, gathering and preservation of the fruits.\nC)  The possessor in bad faith is not entitled to a refund of ornamental expenses.\nD) The possessor in bad faith is entitled to a refund of useful expenses. SUGGESTED ANSWER: D\n"
  },
  {
    "questionId": 26,
    "text": "26. Which phrase most accurately completes the statement – The expenses incurred in improvements for the luxury or mere pleasure shall not be refunded to thew possessor in bad faith: (2012 BAR)\n\n\nA)  but he may remove the objects for which such expenses have been incurred, provided that the thing suffers no injury thereby, and that the lawful possessor does not prefer to retain them.\nB)   and he may not remove the objects for which such expenses have been incurred.\nC)  and he may not remove the objects for which such expenses have been incurred, unless he pays the value they may have at the time he entered into possession.\nD) but he may remove the objects for which such expenses have been incurred. SUGGESTED ANSWER: A\n"
  },
  {
    "questionId": 27,
    "text": "27. A plenary action for the recovery of the possession of real estate, upon mere allegation and proof\nof a better right thereto, and without allegation of proof of title. This action can only be brought\nafter the expiration of one (1) year. What action is being referred to? (2012 BAR)\n\nA)   Accion publiciana\nB)  Accion reinvindicatoria\nC)  Accion interdictal\nD) Quieting of Title\n\nSUGGESTED ANSWER: A\n\n"
  },
  {
    "questionId": 28,
    "text": "28. Action to recover real property based on ownership. Here, the object is the recovery of the dominion over the property as owner. What action is being referred to? (2012 BAR)\n\nA)  Accion publiciana\nB)  Accion reinvindicatoria\nC)  Accion interdictal\nD) Quieting of Title\n\nSUGGESTED ANSWER: B\n\n"
  },
  {
    "questionId": 29,
    "text": "29. A summary action to recover physical or material possession only and must be brought within one\n(1) year from the time the cause of action arises. What action is being referred to? (2012 BAR)\n\nA)  Accion publiciana\nB)  Accion reinvindicatoria\nC)  Accion interdictal\nD) Quieting of Title\n\nSUGGESTED ANSWER: C\n\n"
  },
  {
    "questionId": 30,
    "text": "30. X, the owner, constituted a 10-year usufruct on his land as well as on the building standing on it in Y’s favor. After flood totally destroyed the building 5 years later, X told Y that an act of God terminated the usufruct and that he should vacate the land. Is X, the owner of the land, correct? (2011 BAR)\n\nA)  No, since the building was destroyed through no fault of Y.\nB)  No, since Y still has the right to use the land and the materials left on it.\nC)  Yes, since Y cannot use the land without the building.\nD) Yes, since the destruction of the building without the X’s fault terminated the usufruct.\n\nSUGGESTED ANSWER: B\n\n"
  },
  {
    "questionId": 31,
    "text": "31.  Does Ava have a right to demand from Julia the activation of her right of way? Explain. (2010 BAR)\n\n\nSUGGESTED ANSWER:\n\nYes. Ava has the right to demand from Julia the activation of the right of way, for the following reasons:\n"
  },
  {
    "questionId": 32,
    "text": "32. Assuming Ava opts to demand a right of way from any of the owners of Lots A, B, and D, can she do that? Explain. (2010 Bar Question)\n\nSUGGESTED ANSWER:\n\nYes. Ava has the option to demand a right of way on any of the remaining lots of Franz more so after Franz sold Lot C to Julia. The essential elements of a legal right of way under Article 649 and 650 of the New Civil Code are complied with.\n\nANOTHER SUGGESTED ANSWER:\n\nYes. Ava has the option to demand a right of way from the other lots. The law provides that whenever a piece of land acquired by sale, exchange or partition is surrounded by other estates of the vendor, exchanger, or co-owner, he shall be obliged to grant a right of way without indemnity (Art. 652, NCC).\n\nALTERNATIVE ANSWER:\n\nNo. There was merely a promise to Ava that a right of way shall be granted to her in Lot C if Ava purchased Lot E. The promise was not reduced into writing (Obra v. Baldria, 529 SCRA 621 [2007]). Hence, it was not or could not have been registered as to warn buyers of Lot C about the existence of the easement on the property. Not having been annotated on the TCT to Lot C, the buyer acquired Lot C free from such right of way granted to Ava.\n\n"
  },
  {
    "questionId": 33,
    "text": "33. Acquisitive prescription of a negative easement runs from the time the owner of the dominant estate forbids, in a notarized document, the owner of the servient estate from executing an act which would be lawful without the easement. (2009 Bar Question)\n\nSUGGESTED ANSWER:\n\nTrue. In negative easements, acquisitive prescription runs from the moment the owner of the dominant estate forbade, by an instrument acknowledged before a notary public, the owner of the servient estate from executing an act which would be lawful without the easement (Art. 621, NCC).\n\n"
  },
  {
    "questionId": 34,
    "text": "34. If Carlo is able to legally recover his property, can he require Anthony to account for all the fruits he has harvested from the property while in possession? (2008 BAR)\n\nSUGGESTED ANSWER:\n\nSince Anthony is a possessor in good faith, Anthony cannot be made to account for the fruits he gathered before he was served with summons. A possessor in good faith is entitled to the fruits received before the possession was legally interrupted by the service of summons (Art. 544, CC). After Anthony was served with summons, he became a possessor in bad faith and a builder, planter, sower in bad faith. He can also be made to account for the fruits but he may deduct expenses for production gathering and preservation of the fruits (Art. 1 443, CC).\n\n"
  },
  {
    "questionId": 35,
    "text": "35. If there are standing crops on the property when Carlo recovers possession, can Carlo appropriate them? (2008 BAR)\n\nSUGGESTED ANSWER:\n\nThe value of the standing crops must be prorated depending upon the period of possession and the period of growing and producing the fruits. Anthony is entitled to a part of the net harvest and a part of the expenses of cultivation in proportion to his period of possession. Carlo may appropriate the respective parts subject to prorating the respective periods of possession. However, Carlo may allow Anthony to gather these growing fruits as an indemnity for the expenses of cultivation. If Anthony refuses to accept this concession, he shall lose the right to indemnity under Art. 443 (Art. 545, par. 3, CC).\n\n"
  },
  {
    "questionId": 36,
    "text": "36. Distinguish the following concepts: Occupation v. possession. (2007 BAR) SUGGESTED ANSWER:\nOccupation can take place only with respect to property without an owner while possession can refer to all kinds of property, whether with owner or without an owner. Occupation itself, when proper, confers ownership but possession does not by itself give rise to ownership\n\n"
  },
  {
    "questionId": 37,
    "text": "37. Distinguish antichresis from usufruct. (3%) (2017 BAR) SUGGESTED ANSWER:\n"
  },
  {
    "questionId": 38,
    "text": "38. Tyler owns a lot that is enclosed by the lots of Riley to the North and East, of Dylan to the South, and of Reece to the West. The current route to the public highway is a kilometer’s walk through the northern lot of Riley, but the route is a rough road that gets muddy during the rainy season, and is inconvenient because it is only 2.5 meters wide. Tyler’s nearest access to the public highway would be through the southern lot of Dylan. May Dylan be legally required to afford to Tyler a right of way through his property? Explain your answer. (2017 BAR)\n\nSUGGESTED ANSWER:\n\nDylan may not be legally required to afford Tyler a right of way through his property, because Tyler already has an adequate outlet to the public highway through his Riley’s lot.  One of the requisites for a compulsory grant of right of way is that the estate of the claimant of a right of way must be isolated and without adequate outlet to a public highway. The true standard for the grant of compulsory right of way is “adequacy” of outlet going to a public highway and not the convenience of the dominant estate. In the case at bar, there is already an existing adequate outlet from the dominant estate to a public highway. Even if said outlet be inconvenient, the need to open up another legal easement or servitude is entirely unjustified [Article 649, NCC; Dichoso Jr. v. Marcos, G.R. No. 180282 (2011); Costabella Corp. v. CA, G.R. No.\n80511 (1991)].\n\n"
  },
  {
    "questionId": 39,
    "text": "39. TRUE OR FALSE: Continuous non-apparent easements can be acquired either through title or by prescription. (2017 BAR)\n\nSUGGESTED ANSWER:\n\nFalse. Article 620 of the Civil Code provides that continuous and apparent easement are acquired either by virtue of a title or by prescription of ten years. Continous non-apparent easements and discontinuous ones, whether apparent or not, maybe acquired only by virtue of a title [Art. 622, NCC]. An easement must be both continuous and apparent in order to be subject to acquisition by prescription.\n\n"
  },
  {
    "questionId": 40,
    "text": "40. An easement that can be acquired by prescription: (2014 BAR) A)  Right of way\nB)  Watering of an animal\nC)  Lateral and subjacent support\nD) Light and view\n\n\nSUGGESTED ANSWER:\n\nD. Only continuous and apparent easements may be acquired by prescription\n\n"
  },
  {
    "questionId": 41,
    "text": "41.  In 2005, Andres built a residential house on a lot whose only access to the national highway was a pathway crossing Brando's property. Andres and others have been using this pathway (pathway A) since 1980. In 2006, Brando fenced off his property, thereby blocking Andres' access to the national highway. Andres demanded that part of the fence be removed to maintain his old access route to the highway (pathway A), but Brando refused, claiming that there was another available pathway (pathway B) for ingress and egress to the highway. Andres countered that pathway B has defects, is circuitous, and is extremely inconvenient to use. To settle their dispute, Andres and Brando hired Damian, a geodetic and civil engineer, to survey and examine the two pathways and the surrounding areas, and to determine the shortest and the least prejudicial way through the servient estates. After the survey, the engineer concluded that pathway B is the longer route and will need improvements and repairs, but will not significantly affect the use of Brando's property. On the other hand, pathway. A that had long been in place, is the shorter route but would significantly affect the use of Brando's property. In light of the engineer's findings and the circumstances of the case, resolve the parties' right of way dispute. (2013 BAR)\n\n"
  },
  {
    "questionId": 42,
    "text": "42. TRUE OR FALSE. Only the city or municipal mayor can file a civil action to abate a public nuisance. (2017 BAR)\n\nSUGGESTED ANSWER:\n\nFalse. Article 703 of the New Civil Code provides that a private person may file an action on account of a public nuisance, if it is especially injurious to himself. Thus, a private person may file a civil action to abate a public nuisance that is especially injurious to him.\n\n"
  },
  {
    "questionId": 43,
    "text": "43. Josefa executed a deed of donation covering a one-hectare rice land in favor of her daughter, Jennifer. The deed specifically provides that:  \"For and in consideration of the love and service Jennifer has shown and given to me, I hereby freely, voluntarily and irrevocably donate to her my one-hectare rice land covered by TCT No. 11550, located in San Fernando, Pampanga. This donation shall take effect upon my death.\" The deed also contained Jennifer's signed acceptance, and an attached notarized declaration by Josefa and Jennifer that the land will remain in Josefa's possession and cannot be alienated, encumbered, sold or disposed of while Josefa is still alive. Advise Jennifer on whether the deed is a donation inter vivos or mortis causa and explain the reasons supporting your advice. (2013 BAR)\n\nSUGGESTED ANSWER:\nThe donation is a donation inter vivos. When the donor intends that the donation shall take effect during the lifetime of the donor, though the property shall not be delivered till after the donor’s death, this shall be a donation inter vivos (Art. 729). The Civil Code prefers inter vivos transmissions. Moreover, mortis causa donations should follow the formalities of a will (Art. 728). Here there is no showing that such formalities  were  followed.  Thus,  it  is  favorable  to  Jennifer  that  the  deed  is  a  donation  inter vivos.       Furthermore, what is most significant in determining the type of donation is the absence of stipulation that the donor could revoke the donation; on the contrary, the deeds expressly declare them to be “irrevocable,” a quality absolutely incompatible with the idea of conveyances mortis causa where revocability is the essence of the act, to the extent that a testator cannot lawfully waive or restrict his right of revocation. The provisions of the deed of donation which state that the same will only take effect upon the death of the donor and that there is a prohibition to alienate, encumber, dispose, or sell the same should be harmonized with its express irrevocability (Austria-Magat v. CA, G.R. No. 106755, February 1, 2002).\n\nH.   Modes of acquiring ownership\n\n"
  },
  {
    "questionId": 44,
    "text": "44. X bought a land from Y, paying him cash. Since they were friends, they did not execute any document of sale. After 7 years, the heirs of X asked Y to execute a deed of absolute sale to formalize the verbal sale to their father. Unwilling to do so, X’s heirs filed an action for specific performance against Y. Will their action prosper? (2011 BAR)\n\nA)  No, after more than 6 years, the action to enforce the verbal agreement has already elapsed.\n\nB)  No, since the sale cannot under the Statute of Frauds be enforced. C)  Yes, since X bought the land and paid Y for it.\nD) Yes, after full payment, the action became imprescriptible. SUGGESTED ANSWER: A\n"
  },
  {
    "questionId": 45,
    "text": "45. An action for reconveyance of a registered piece of land may be brought against the owner\nappearing on the title based on a claim that the latter merely holds such title in trust for the\nplaintiff. The action prescribes, however, within 10 years from the registration of the deed or the date of the issuance of the certificate of title of the property as long as the trust had not been repudiated. What is the exception to this 10-year prescriptive period? (2011 BAR)\n\nA)  When the plaintiff had no notice of the deed or the issuance of the certificate of title. B)  When the title holder concealed the matter from the plaintiff.\nC)  When fortuitous circumstances prevented the plaintiff from filing the case sooner. D) When the plaintiff is in possession of the property.\n\nSUGGESTED ANSWER: D\n\n"
  },
  {
    "questionId": 46,
    "text": "46. What is the prescriptive period for filing an action for revocation of a donation based on acts of ingratitude of the donee? (2011 BAR)\n\nA)  5 years from the perfection of the donation. B)  1 year from the perfection of the donation. C)  4 years from the perfection of the donation. D) Such action does not prescribe.\n\nSUGGESTED ANSWER: B\n\n"
  },
  {
    "questionId": 47,
    "text": "47. Anthony bought a piece of untitled agricultural land from Bert, Bert, in turn, acquired the property by forging Carlo’s signature in a deed of sale over the property. Carlo had been in possession of the property for 8 years, declared it for tax purposes, and religiously paid all taxes due on the property. Anthony is not aware of the defect in Bert’s title, but has been in actual physical possession of the property from the time he bought it from Bert, who had never been in possession. Anthony has since then been in possession of the property for one year.  Can Anthony acquire ownership of the property by acquisitive prescription? How many more years does he have to possess it to acquire ownership? (2008 BAR)\n\nSUGGESTED ANSWER:\n\nYes, Anthony can acquire ownership of the property by ordinary acquisitive prescription which requires just title and good faith (Art. 1117, cc). There was just title because a deed of sale was issued in his favor even though it was forged, which fact he was not aware of. He needs to possess the land in good faith and in the concept of owner for a total of ten years in order to acquire ownership. Since Anthony possessed the land for only one year, he has not completed the ten-year period. Even if Anthony tacks the 8-year period of possession by Carlo who in the deed of sale is supposed to be his grantor or predecessor in interest (Article 1138 [I], CC), the period is still short of ten years.\n\n"
  },
  {
    "questionId": 48,
    "text": "48. Distinguish the following concepts: (a) Occupation v. possession. (2007 BAR)\n\n\nSUGGESTED ANSWER:\n\nOccupation can take place only with respect to property without an owner while possession can refer to all kinds of property, whether with owner or without an owner. Occupation itself, when proper, confers ownership but possession does not by itself give rise to ownership\n\nALTERNATIVE ANSWER:\n\nOccupation is an original mode of acquiring ownership (Art. 712, NCC). Things appropriable by nature which are without an owner, such as animals that are the object of hunting and fishing, hidden treasure and abandoned movables, are acquired by occupation (Art. 713, NCC). However, ownership of a piece of land cannot be acquired by occupation (Art. 714, NCC). On the other hand, possession is the holding of a thing or the enjoyment of a right, as provided in Article 523 of the New Civil Code. Possession can be in the concept of an owner or in the concept of a holder (Art. 525, NCC).\n\n"
  },
  {
    "questionId": 49,
    "text": "49. Illegal and impossible conditions in a simple donation v. illegal and impossible conditions in an onerous donation. (2007 BAR)\n\nSUGGESTED ANSWER:\n\nIllegal and impossible conditions in a simple donation are considered as not written. Such conditions shall, therefore, be disregarded but the donation remains valid (Article 727, NCC).\n\nOn the other hand, illegal and impossible conditions imposed in an onerous donation shall annul the donation (Article 1183, NCC). This is so, because onerous donations are governed by the law on contracts (Article 733, NCC).\n\n"
  },
  {
    "questionId": 50,
    "text": "50. In 1986, Jennifer and Brad were madly in love. In 1989, because a certain Picasso painting reminded Brad of her, Jennifer acquired it and placed it in his bedroom. In 1990, Brad and Jennifer broke up. While Brad was mending his broken heart, he met Angie and fell in love. Because the Picasso painting reminded Angie of him, Brad in his will bequeathed the painting to Angie. Brad died in 1995. Saddened by Brad’s death, Jennifer asked for the Picasso painting as a remembrance of him. Angie refused and claimed that Brad, in his will, bequeathed the painting to her. Is Angie correct? Why or why not? (2007 BAR)\n\nSUGGESTED ANSWER:\n\nNO. Angie is not correct. The Picasso painting was not given or donated by Jennifer to Brad.\nShe merely “placed it in his bedroom”. Hence, she is still the owner of the painting. Not being the owner\nof the Picasso painting, Brad cannot validly bequeath the same to Angie (Art. 930, NCC). Even if the painting was impliedly given or donated by Jennifer to Brad, the donation and acceptance of a movable worth more than 5,000 pesos must be in writing, otherwise the donation is void. The donation being void, Jennifer remained the owner of the Picasso painting and Brad could not have validly disposed of said painting in favor of Angie in his will.\n\nALTERNATIVE ANSWER:\n\nYes, Angie is correct. Even assuming that there was a void donation because the donation was not in writing, Brad, who was in uninterrupted possession of the Picasso painting from 1989 to 1995, lasting for six (6) years prior to his death, Brad has already acquired ownership of the painting through acquisitive prescription. Under Article 1132 of the New Civil Code, Ownership of movables prescribes through continuous possession for four (4) years in good faith and for eight (8) years without need of any other\n\nconditions. A void donation may be the basis of possession in the concept of owner and of just title for purposes of acquisitive prescription.\n\n"
  },
  {
    "questionId": 51,
    "text": "51.  Write \"TRUE' if the statement is true or “FALSE” if the statement is false. If the statement is\nFALSE, state the reason. x x x\nIf a man commits several acts of sexual infidelity, particularly in 2002, 2003, 2004, 2005, the prescriptive period to file for legal separation runs from 2002. (2007 BAR)\n\nSUGGESTED ANSWER:\n\nFALSE. The five-year prescriptive period for filing legal separation runs from the occurrence of each act of sexual infidelity. Hence, the prescriptive period for the sexual infidelity committed in 2002 runs from\n2002; for the sexual infidelity committed in 2003, the prescriptive period runs from 2003 and so on. The action for legal separation for the last act of sexual infidelity in 2005 will prescribe in 2010.\n\n"
  },
  {
    "questionId": 52,
    "text": "Section 1 0f P.D. NO. 755 states:\nSection 1. Declaration of National Policy – It is hereby declared that the policy of the State is to\nprovide readily available credit facilities to the coconut farmers at preferential rates, that this policy\ncan be expeditiously and efficiently realized by the implementation of the “Agreement for the\nAcquisition of a Commercial Bank for the Benefit of the Coconut Farmers’ executed by the Philippine Coconut Authority, the  terms  of  which  ’Agreement’ are  hereby  incorporated by reference; xxx”\n\nA copy of the Agreement was not attached to the Presidential Decree.\n\nP.D. No: 755 was published in the Official Gazette but the text of the Agreement described in Section 1 was not published. Can the Agreement in question be accorded the status of a law? Explain. (5%) (2016 Bar Question)\n\n"
  },
  {
    "questionId": 53,
    "text": "2.   Is it necessary for Ted to file a petition for judicial recognition of the decree of divorce he obtained in Canada before he can contract a second marriage in the Philippines? (2014 Bar Question)\n\n\n"
  },
  {
    "questionId": 54,
    "text": "3.   Congress passed a law imposing taxes on income earned out of a particular activity that was not previously taxed. The law, however, taxed incomes already earned within the fiscal year when the law took effect. Is the law valid? (2011 Bar Question)\n\nA) No, because laws are intended to be prospective, not retroactive.\nB) No, the law is arbitrary in that it taxes income that has already been spent. C) Yes, since tax laws are the lifeblood of the nation.\nD) Yes, tax laws are an exception; they can be given retroactive effect.\n\n"
  },
  {
    "questionId": 55,
    "text": "4.   The doctrine of stare decisis prescribes adherence to precedents in order to promote the stability of the law. But the doctrine can be abandoned: (2011 Bar Question)\n\nA) When adherence to it would result in the Government’s loss of its case.\nB) When the application of the doctrine would cause great prejudice to a foreign national. C) When necessary to promote the passage of a new law\nD) When the precedent has ceased to be beneficial and useful. SUGGESTED ANSWER: D.\nB.Conflict of laws (Private International Law)\n\n"
  },
  {
    "questionId": 56,
    "text": "5.   Ted, married to Annie, went to Canada to work. Five (5) years later, Ted became a naturalized Canadian citizen. He returned to the Philippines to convince Annie to settle in Canada. Unfortunately, Ted discovered that Annie and his friend Louie were having an affair. Deeply hurt, Ted returned to Canada and filed a petition for divorce which was granted. In December 2013, Ted decided to marry his childhood friend Corazon in the Philippines. In preparation for the wedding, Ted went to the Local Civil Registry of Quezon City where his marriage contract with Annie was registered. He asked the Civil Register to annotate the decree of divorce on his marriage contract with Annie. However, he was advised by the National Statistics Office (NSO) to file a petition for judicial recognition of the decree of divorce in the Philippines.\n\nIs it necessary for Ted to file a petition for judicial recognition of the decree of divorce he obtained in Canada before he can contract a second marriage in the Philippines? (2014 Bar Question)\n\n\n"
  },
  {
    "questionId": 57,
    "text": "6.   This attribute or incident of a case determine whether it is a conflict-of-laws case or one covered by domestic law. (2012 Bar Question)\n\nA) Cause of action B) Foreign element C) Jurisdiction\nD) Forum non conveniens\n\n\n"
  },
  {
    "questionId": 7,
    "text": "7.   Atty. BUKO, a Filipino, executed a will while he was in Spain. The attestation clause of the said will does not contain Buko’s signature. It is valid under Spanish law. At its probate in Manila, it is being opposed on the ground that the attestation clause does not contain BUKO’s signature. Is the opposition correct? Choose the best answer. (2012 Bar Question)\n\nA) Yes, because it is a fatal defect.\nB) Yes, the will is not valid under Philippine law.\nC) No, attestation clause is not an act of the testator. D) No, the governing law is Spanish law.\n\n\n"
  },
  {
    "questionId": 58,
    "text": "8.   Even if the applicable law is a foreign law, a count in the Philippines may be constrained to apply\nPhilippine law under any of the following instances, except: (2012 Bar Question)\n\nA) when the foreign law, judgment or contract is contrary to a sound and important public policy of the forum;\nB) when the property subject of the case is located outside of the Philippines; C) when the foreign law or judgment is penal in nature;\nD) when the foreign law is procedural in nature.\n\n\n"
  },
  {
    "questionId": 59,
    "text": "9.   If a will is executed by a testator who was born a Filipino citizen but became naturalized Japanese citizen at the time of his death, what law will govern its testamentary provisions if the will is executed in China and the property being disposed is located in Indonesia? (2012 Bar Question)\n\nA) Chinese law\nB) Philippine law\nC) Indonesia law\nD) Japanese law\n\n\n"
  },
  {
    "questionId": 60,
    "text": "10.  A Japanese national and a Filipino national entered into a contract for services in Thailand. The services will be rendered in Singapore. In case of breach, what law will govern? (2012 Bar Question)\n\nA) Thailand law B) Philippine law C) Singapore law D) Japanese law\n\n\n"
  },
  {
    "questionId": 61,
    "text": "11.  Pedro (Filipino) and his wife Jane (American) executed a joint will in Canada, where such joint will is valid. In case the joint will is probated in Japan, what law will govern the formalities of the joint will? (2012 Bar Question)\n\nA) American law B) Philippine law C) Canadian law D) Japanese law\n\n\n\n"
  },
  {
    "questionId": 62,
    "text": "12.  A French national revokes his will in Japan where he is domiciled. He then changed his domicile to the Philippines where he died. The revocation of his will in Japan is valid under Japanese law but invalid under Philippine law. The affected heir is a Malaysian national residing in the Philippines. What law will apply? (2012 Bar Question)\n\nA) Japanese law B) Philippine law C) French law\nD) Malaysian law\n\n\n"
  },
  {
    "questionId": 63,
    "text": "13.  Pedro (Filipino) and Bill (American) entered into a contract in Australia, whereby it was agreed that Pedro will build a commercial building for Bill in the Philippines, and in payment for the construction, Bill will transfer and convey his cattle ranch located in Japan in favor of Pedro. In case Pedro performs his obligation, but Bill fails or refuses to pay, what law will govern? (2012 Bar Question)\n\nA) American law B) Philippine law C) Australian law D) Japanese law\n\n\n"
  },
  {
    "questionId": 64,
    "text": "14.  An Australian living in the Philippines acquired shares of stock worth P10 million in food manufacturing companies. He died in Manila, leaving a legal wife and a child in Australia and a live-in partner with whom he had two children in Manila. He also left a will, done according to Philippine laws, leaving all his properties to his live-in partner and their children. What law will govern the validity of the disposition in the will? (2011 Bar Question)\n\nA)  Australia law since his legal wife and legitimate child are Australians and domiciled in\nAustralia.\nB)  Australian law since the intrinsic validity of the provisions of a will is governed by the\ndecedent’s national law.\nC)  Philippine law since the decedent died in Manila and he executed his will according to such law.\nD) Philippine law since the decedent’s properties are in the Philippines. SUGGESTED ANSWER: B.\n"
  },
  {
    "questionId": 65,
    "text": "15.  TRUE or FALSE. Answer TRUE if the statement is true, or FALSE if the statement is false.\nExplain your answer in not more than two (2) sentences.\n\nThe doctrine of “processual presumption” allows the court of the forum to presume that the foreign law applicable to the case is the same as the local or domestic law. (2009 Bar Question)\n\n\n\n"
  },
  {
    "questionId": 66,
    "text": "16.  On December 1, 2000, Dr. Juanito Fuentes executed a holographic will, wherein he gave nothing to his recognized illegitimate son, Jay. Dr. Fuentes left for the United States, passed the New York medical licensure examinations, resided therein, and became a naturalized American citizen. He died in New York in 2007. The laws of New York do not recognize holographic wills or compulsory heirs. (2009 Bar Question)\n\nA)  Can the holographic will of Dr. Fuentes be admitted to probate in the Philippines? Why or why not?\n\nB)  Assuming that the will is probated in the Philippines, can Jay validly insist that he be given his legitime? Why or why not?\n\n"
  },
  {
    "questionId": 67,
    "text": "17.  Emmanuel and Margarita, American citizens and employees of the U.S. State Department, got married in the African state of Kenya where sterility is a ground for annulment of marriage. Thereafter, the spouses were assigned to the U.S. Embassy in Manila. On the first year of the spouses’ tour of duty in the Philippines, Margarita filed an annulment case against Emmanuel before a Philippine court on the ground of her husband’s sterility at the time of the celebration of the marriage.\n\nA)  Will the suit prosper? Explain your answer. (2009 Bar Question) SUGGESTED ANSWER:\nNo, the suit will not prosper. As applied to foreign nationals with respect to family relations and status of persons, the nationality principle set forth in Article 15 of the Civil Code will govern the relations of Emmanuel and Margarita. Since they are American citizens, the governing law as to the ground for annulment is not Kenyan law which Margarita invokes in support of sterility as such ground; but should be U.S. law, which is the national law of both Emmanuel and Margarita as recognized under Philippine\nlaw.\n\n"
  },
  {
    "questionId": 68,
    "text": "18.  If Ligaya, a Filipino citizen residing in the United States, file a petition for change of name before the District Court of New York, what law shall apply? Explain. (2009 Bar Question)\n\n\n"
  },
  {
    "questionId": 69,
    "text": "19.  If Henry, an American citizen residing in the Philippines, files a petition for change of name before a Philippine court, what law shall apply? Explain. (2009 Bar Question)\n\n\n"
  },
  {
    "questionId": 70,
    "text": "20. Write \"TRUE' if the statement is true or “FALSE” if the statement is false. If the statement is\nFALSE, state the reason.\n\nRoberta, a Filipino, 17 years of age, without the knowledge of his parents, can acquire a house in Australia because Australian Laws allow aliens to acquire property from the age of 16. (2007 Bar Question)\n\nC.Human relations (Articles 19-22)\n\n"
  },
  {
    "questionId": 71,
    "text": "21.  When one exercises a right recognized by law, knowing that he thereby causes an injustice to another, the latter is entitled to recover damages. This is known as the principle of (2011 Bar Question)\n\nA) res ipsa loquitur.\nB) damnum absque injuria. C) vicarious liability.\nD) abuse of rights.\n\n"
  },
  {
    "questionId": 72,
    "text": "22. Six tenants sued X, the landowner, for willfully denying them water for their farms, which water happened to flow from land under X’s control, his intention being to force them to leave his properties. Is X liable for his act and why? (2011 Bar Question)\n\nA)  No, because the tenants must be content with waiting for rainfall for their farms. B)  No, since X owns both the land and the water.\nC)  Yes, because the tenants’ farms have the natural right of access to water wherever it is located.\nD) Yes, since X willfully caused injury to his tenants contrary to morals, good customs or public policy.\n\n"
  },
  {
    "questionId": 73,
    "text": "23. Janice and Jennifer are sisters. Janice sued Jennifer and Laura, Jennifer’s business partner for recovery of property with damages. The complaint did not allege that Janice exerted earnest efforts to come to a compromise with the defendants and that such efforts failed. The judge dismissed the complaint outright for failure to comply with a condition precedent. Is the dismissal in order? (2011 Bar Question)\n\nA)"
  },
]